<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyName>Game.Global</AssemblyName>
        <RootNamespace>Game</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\shared\Domain\Domain.csproj" />
        <ProjectReference Include="..\..\..\shared\Game\Game.csproj" />
        <ProjectReference Include="..\..\..\shared\Protocol\Protocol.csproj" />
        <ProjectReference Include="..\..\Infrastructure\Discovery\Environment\Environment.csproj" />
        <ProjectReference Include="..\..\Infrastructure\Discovery\Services\Services.csproj" />
        <ProjectReference Include="..\..\Infrastructure\Messaging\Interfaces\Interfaces.csproj" />
        <ProjectReference Include="..\..\Infrastructure\Orleans\Common\Common.csproj" />
        <ProjectReference Include="..\GamePlay\Board\Board.csproj" />
        <ProjectReference Include="..\GamePlay\Cards\Cards.csproj" />
        <ProjectReference Include="..\GamePlay\Commands\Commands.csproj" />
        <ProjectReference Include="..\GamePlay\Context\Context.csproj" />
        <ProjectReference Include="..\GamePlay\Players\Players.csproj" />
        <ProjectReference Include="..\Session\Session.csproj"/>
    </ItemGroup>

</Project>
