using System;
using System.Collections.Generic;

namespace ContainerGenerator {
    internal static class InjectorEmitter {
        public static GeneratedInjectorSource Emit(InjectorModel model) {
            var diagnostics = new List<DiagnosticInfo>();

            if (model.IsNested) {
                diagnostics.Add(new DiagnosticInfo(InjectorDescriptors.NestedNotSupported, model.Location, model.SymbolName));
                return Fail(model, diagnostics);
            }

            if (model.IsGeneric) {
                diagnostics.Add(new DiagnosticInfo(InjectorDescriptors.GenericNotSupported, model.Location, model.SymbolName));
                return Fail(model, diagnostics);
            }

            if (model.MultipleConstruct) {
                diagnostics.Add(new DiagnosticInfo(InjectorDescriptors.MultipleConstruct, model.Location, model.SymbolName));
                return Fail(model, diagnostics);
            }

            if (model.HasConstruct && model.ConstructIsGeneric) {
                diagnostics.Add(new DiagnosticInfo(InjectorDescriptors.GenericConstruct, model.Location, model.SymbolName));
                return Fail(model, diagnostics);
            }

            if (model.HasConstruct && model.ConstructAccessible == false) {
                diagnostics.Add(new DiagnosticInfo(InjectorDescriptors.InaccessibleConstruct, model.Location, model.SymbolName));
                return Fail(model, diagnostics);
            }

            var writer = new CodeWriter();
            writer.AppendLine("// <auto-generated/>");
            writer.AppendLine("#pragma warning disable");
            writer.AppendLine("using System;");
            writer.AppendLine();

            // Same assembly as the target type, but Internal.Generated so the class name
            // does not collide with VContainer's `{Type}GeneratedInjector` until that package is gone.
            writer.AppendLine("namespace Internal.Generated {");
            writer.AppendLine("    internal sealed class " + model.InjectorTypeName + " : global::Internal.IInjector {");

            var indent = "        ";
            var deeper = "            ";
            WriteBody(writer, model, indent, deeper);

            writer.AppendLine("    }");
            writer.AppendLine("}");

            return new GeneratedInjectorSource(
                model.HintName,
                writer.ToString(),
                model,
                new EquatableArray<DiagnosticInfo>(diagnostics.ToArray()));
        }

        public static string EmitRegistry(
            string assemblyName,
            bool hasUnityInit,
            IReadOnlyList<InjectorModel> models) {
            var safe = TypeNames.SafeAssembly(assemblyName);
            var writer = new CodeWriter();
            writer.AppendLine("// <auto-generated/>");
            writer.AppendLine("#pragma warning disable");
            writer.AppendLine("using System;");
            writer.AppendLine();
            writer.AppendLine("namespace Internal {");
            writer.AppendLine("    public static class ContainerInjectors_" + safe + " {");
            if (hasUnityInit)
                writer.AppendLine("        [global::UnityEngine.RuntimeInitializeOnLoadMethod(global::UnityEngine.RuntimeInitializeLoadType.SubsystemRegistration)]");

            writer.AppendLine("        public static void Register() {");
            for (var i = 0; i < models.Count; i++) {
                var model = models[i];
                writer.AppendLine(
                    "            global::Internal.ContainerInjectors.Register(typeof(" + model.FullTypeName +
                    "), slots => new global::Internal.Generated." + model.InjectorTypeName + "(slots));");
            }

            // Nested generics are skipped (CING002). Marking the assembly covered would make
            // those types throw at Build (locked 10). Mark when the generator covers them.
            writer.AppendLine("        }");
            writer.AppendLine("    }");
            writer.AppendLine("}");
            return writer.ToString();
        }

        private static void WriteBody(CodeWriter writer, InjectorModel model, string indent, string deeper) {
            var slotCount = model.ConstructorParameters.Count + model.ConstructParameters.Count;
            writer.AppendLine(indent + "public " + model.InjectorTypeName + "(int[] slots) {");
            for (var i = 0; i < slotCount; i++)
                writer.AppendLine(deeper + "_slot" + i + " = slots[" + i + "];");

            writer.AppendLine(indent + "}");
            writer.AppendLine();
            for (var i = 0; i < slotCount; i++)
                writer.AppendLine(indent + "private readonly int _slot" + i + ";");

            if (slotCount > 0)
                writer.AppendLine();

            writer.AppendLine(indent + "public object Create(global::Internal.IResolvePlan plan) {");
            WriteCreate(writer, model, deeper);
            writer.AppendLine(indent + "}");
            writer.AppendLine();
            writer.AppendLine(indent + "public void Construct(object instance, global::Internal.IResolvePlan plan) {");
            WriteConstruct(writer, model, deeper);
            writer.AppendLine(indent + "}");
        }

        private static void WriteCreate(CodeWriter writer, InjectorModel model, string indent) {
            if (model.IsUnityObject) {
                writer.AppendLine(indent + "_ = plan;");
                writer.AppendLine(indent + "throw new global::System.NotSupportedException(\"UnityEngine.Object: " +
                                  model.FullTypeName + " cannot be constructed with new.\");");
                return;
            }

            if (model.ConstructorFound == false || model.ConstructorAccessible == false) {
                writer.AppendLine(indent + "_ = plan;");
                writer.AppendLine(indent + "throw new global::System.NotSupportedException(\"No accessible constructor for " +
                                  model.FullTypeName + ".\");");
                return;
            }

            if (model.ConstructorParameters.Count == 0) {
                writer.AppendLine(indent + "var instance = new " + model.FullTypeName + "();");
            }
            else {
                writer.AppendLine(indent + "var instance = new " + model.FullTypeName + "(");
                for (var i = 0; i < model.ConstructorParameters.Count; i++) {
                    var comma = i + 1 < model.ConstructorParameters.Count ? "," : "";
                    writer.AppendLine(indent + "    plan.Get<" + model.ConstructorParameters[i].TypeFullName + ">(_slot" + i + ")" + comma);
                }

                writer.AppendLine(indent + ");");
            }

            writer.AppendLine(indent + "Construct(instance, plan);");
            writer.AppendLine(indent + "return instance;");
        }

        private static void WriteConstruct(CodeWriter writer, InjectorModel model, string indent) {
            if (model.HasConstruct == false) {
                writer.AppendLine(indent + "_ = instance;");
                writer.AppendLine(indent + "_ = plan;");
                return;
            }

            writer.AppendLine(indent + "var typed = (" + model.FullTypeName + ")instance;");
            if (model.ConstructParameters.Count == 0) {
                writer.AppendLine(indent + "_ = plan;");
                writer.AppendLine(indent + "typed.Construct();");
                return;
            }

            var offset = model.IsUnityObject || model.ConstructorAccessible == false
                ? 0
                : model.ConstructorParameters.Count;
            writer.AppendLine(indent + "typed.Construct(");
            for (var i = 0; i < model.ConstructParameters.Count; i++) {
                var comma = i + 1 < model.ConstructParameters.Count ? "," : "";
                writer.AppendLine(indent + "    plan.Get<" + model.ConstructParameters[i].TypeFullName + ">(_slot" + (offset + i) + ")" + comma);
            }

            writer.AppendLine(indent + ");");
        }

        private static GeneratedInjectorSource Fail(InjectorModel model, List<DiagnosticInfo> diagnostics) {
            return new GeneratedInjectorSource(
                model.HintName,
                null,
                model,
                new EquatableArray<DiagnosticInfo>(diagnostics.ToArray()));
        }
    }
}
