using System.Collections.Generic;
using System.Text;

namespace Internal
{
    internal static class ContainerGraphAssetWriter
    {
        // Имя не должно кончаться на Assets.cs: такие файлы в папках Generated считает своими
        // AssetsCatalogClassGenerator и удаляет как устаревшие.
        public const string OutputPath =
            "Assets/Common/Internal/Runtime/Tools/Container/Generated/ContainerGraph.AssetMap.cs";

        public static void Write(IReadOnlyList<ContainerGraphAsset> assets)
        {
            var prefabs = new List<ContainerGraphAsset>();
            var scenes = new List<ContainerGraphAsset>();

            for (var i = 0; i < assets.Count; i++)
            {
                var asset = assets[i];

                if (asset.AssetPath.EndsWith(".unity"))
                    scenes.Add(asset);
                else
                    prefabs.Add(asset);
            }

            GeneratedFile.WriteIfChanged("ContainerGraph", OutputPath, Build(prefabs, scenes));
        }

        private static string Build(List<ContainerGraphAsset> prefabs, List<ContainerGraphAsset> scenes)
        {
            var builder = new StringBuilder();
            builder.AppendLine("// Auto-generated by ContainerGraphPostprocessor. Do not edit manually.");
            WriteAttributes(builder, prefabs);
            WriteAttributes(builder, scenes);
            builder.AppendLine("namespace Internal {");
            builder.AppendLine("    [global::Unity.Scripting.LifecycleManagement.NoAutoStaticsCleanup]");
            builder.AppendLine("    public static partial class ContainerGraph {");
            WriteArray(builder, "Prefabs", prefabs);
            builder.AppendLine();
            WriteArray(builder, "Scenes", scenes);
            builder.AppendLine("    }");
            builder.AppendLine("}");
            return builder.ToString();
        }

        private static void WriteAttributes(StringBuilder builder, List<ContainerGraphAsset> assets)
        {
            for (var i = 0; i < assets.Count; i++)
            {
                var asset = assets[i];
                builder.AppendLine("[assembly: global::Internal.ContainerGraphAsset(");
                builder.AppendLine("    " + Literal(asset.AssetPath) + ",");
                builder.AppendLine("    " + Literal(asset.HolderType) + ",");
                builder.AppendLine("    new string[] {");

                for (var t = 0; t < asset.ComponentTypes.Length; t++)
                {
                    var comma = t + 1 < asset.ComponentTypes.Length ? "," : "";
                    builder.AppendLine("        " + Literal(asset.ComponentTypes[t]) + comma);
                }

                builder.AppendLine("    })]");
            }

            if (assets.Count > 0)
                builder.AppendLine();
        }

        private static void WriteArray(StringBuilder builder, string name, List<ContainerGraphAsset> assets)
        {
            builder.AppendLine("        public static readonly ContainerGraphAsset[] " +
                               name +
                               " = new ContainerGraphAsset[] {");

            for (var i = 0; i < assets.Count; i++)
            {
                var asset = assets[i];
                builder.AppendLine("            new ContainerGraphAsset(");
                builder.AppendLine("                " + Literal(asset.AssetPath) + ",");
                builder.AppendLine("                " + Literal(asset.HolderType) + ",");
                builder.AppendLine("                new string[] {");

                for (var t = 0; t < asset.ComponentTypes.Length; t++)
                {
                    var comma = t + 1 < asset.ComponentTypes.Length ? "," : "";
                    builder.AppendLine("                    " + Literal(asset.ComponentTypes[t]) + comma);
                }

                builder.AppendLine("                })" + (i + 1 < assets.Count ? "," : ""));
            }

            builder.AppendLine("        };");
        }

        private static string Literal(string value)
        {
            if (value == null)
                value = "";
            return "@\"" + value.Replace("\"", "\"\"") + "\"";
        }
    }
}