#!/usr/bin/env bash
# Deploy the Unity WebGL client to the Coolify host.
#
# Uploads client/build into <DEPLOY_PATH>/releases/<tag> over SSH and flips
# the `current` symlink that the nginx container (client/deploy/docker-compose.yaml)
# serves. The container is never redeployed — the swap is atomic and instant.
#
# Credentials live outside the repo, in ~/.config/mines-leader/deploy.env:
#
#   DEPLOY_HOST=root@your-coolify-host      # ssh target
#   DEPLOY_PATH=/data/mines-leader-web      # must match the compose bind mount
#   DEPLOY_SSH_KEY=~/.ssh/id_ed25519        # optional, for key auth
#
# Password auth: put the password (and nothing else) in
# tools/scripts/.deploy-password — gitignored, read via `sshpass -f` so it never
# shows up in the process list. Requires the `sshpass` package.
#   KEEP_RELEASES=5                         # optional, default 5
#   FORCE=1                                 # optional, redeploy a build that is already live
#
# The build itself is made in the editor (Tools/Build/WebGL) — that is also
# where the Web Stripping Tool post-processes it.
#
# Usage:
#   tools/scripts/deploy-webgl.sh                  # upload the existing build
#   tools/scripts/deploy-webgl.sh --list           # show releases on the server
#   tools/scripts/deploy-webgl.sh --rollback <tag> # point `current` at an old release
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
BUILD_DIR="$ROOT/client/build"
ENV_FILE="${DEPLOY_ENV_FILE:-$HOME/.config/mines-leader/deploy.env}"

if [[ -f "$ENV_FILE" ]]; then
    set -a
    source "$ENV_FILE"
    set +a
fi

: "${DEPLOY_HOST:?set DEPLOY_HOST in $ENV_FILE}"
DEPLOY_PATH="${DEPLOY_PATH:-/data/mines-leader-web}"
KEEP_RELEASES="${KEEP_RELEASES:-5}"

SSH_OPTS=()
if [[ -n "${DEPLOY_SSH_KEY:-}" ]]; then
    SSH_OPTS=(-i "${DEPLOY_SSH_KEY/#\~/$HOME}")
fi

# Password auth, if a password file is present: `-f` keeps the secret out of the
# process list, unlike `sshpass -p`.
PASS_FILE="${DEPLOY_PASSWORD_FILE:-$ROOT/tools/scripts/.deploy-password}"
SSH_CMD=(ssh)
if [[ -f "$PASS_FILE" ]]; then
    if ! command -v sshpass >/dev/null; then
        echo "$PASS_FILE exists but sshpass is not installed (sudo pacman -S sshpass)." >&2
        exit 1
    fi
    SSH_CMD=(sshpass -f "$PASS_FILE" ssh)
    # Every ssh/rsync invocation authenticates separately; without this a typo in
    # the password file turns into five prompts instead of one clear failure.
    SSH_OPTS+=(-o PreferredAuthentications=password -o PubkeyAuthentication=no -o BatchMode=no)
fi

remote() { "${SSH_CMD[@]}" "${SSH_OPTS[@]}" "$DEPLOY_HOST" "$@"; }

case "${1:-}" in
    --list)
        remote "ls -1 '$DEPLOY_PATH/releases' && echo '--- current:' && readlink '$DEPLOY_PATH/current'"
        exit 0
        ;;
    --rollback)
        target="${2:?usage: --rollback <tag>}"
        remote "test -d '$DEPLOY_PATH/releases/$target'"
        remote "cd '$DEPLOY_PATH' && ln -sfn 'releases/$target' current.tmp && mv -Tf current.tmp current"
        echo "Rolled back to $target"
        exit 0
        ;;
    "") ;;
    *)
        echo "Unknown option: $1" >&2
        exit 2
        ;;
esac

if [[ ! -f "$BUILD_DIR/index.html" ]]; then
    echo "No WebGL build at $BUILD_DIR — build from the editor (Tools/Build/WebGL)." >&2
    exit 1
fi

# The tag names HEAD, not the build, so re-uploading an old client/build looks
# like a fresh release while the browser (correctly) keeps answering 304.
# build-guid.txt is regenerated by every Unity build — compare it with the live one.
local_guid="$(cat "$BUILD_DIR/build-guid.txt" 2>/dev/null || true)"
live_guid="$(remote "cat '$DEPLOY_PATH/current/build-guid.txt' 2>/dev/null" || true)"
if [[ -n "$local_guid" && "$local_guid" == "$live_guid" && "${FORCE:-0}" != 1 ]]; then
    echo "client/build is the build that is already live (build-guid $local_guid)." >&2
    echo "Rebuild in the editor first (Tools/Build/WebGL), or set FORCE=1 to redeploy it anyway." >&2
    exit 1
fi

build_time="$(stat -c %Y "$BUILD_DIR/index.html")"
head_time="$(git -C "$ROOT" log -1 --format=%ct)"
if (( head_time > build_time )); then
    echo "warning: client/build ($(date -d "@$build_time" '+%F %T')) is older than HEAD ($(date -d "@$head_time" '+%F %T'))." >&2
fi

TAG="${TAG:-$(date +%Y%m%d-%H%M%S)-$(git -C "$ROOT" rev-parse --short HEAD)}"
RELEASE="$DEPLOY_PATH/releases/$TAG"

echo "==> Uploading $(du -sh "$BUILD_DIR" | cut -f1) to $DEPLOY_HOST:$RELEASE"
remote "mkdir -p '$DEPLOY_PATH/releases'"

# nginx.conf is bind-mounted straight from this directory (see
# client/deploy/docker-compose.yaml), so it ships with the deploy. It is only a
# couple of KB — always send it and let rsync report whether it actually changed.
conf_changed="$(rsync -ai --chmod=F644 -e "${SSH_CMD[*]} ${SSH_OPTS[*]}" \
    "$ROOT/client/deploy/nginx.conf" "$DEPLOY_HOST:$DEPLOY_PATH/nginx.conf")"

# --link-dest hardlinks unchanged files against the live release, so a redeploy
# only transfers the payloads that actually changed.
# --chmod: Unity writes the build with 0600, which nginx (running as its own
# uid inside the container) cannot read — without this every payload 403s.
rsync -az --delete --chmod=D755,F644 \
    -e "${SSH_CMD[*]} ${SSH_OPTS[*]}" \
    --link-dest="$DEPLOY_PATH/current" \
    "$BUILD_DIR/" "$DEPLOY_HOST:$RELEASE/"

# The link target is RELATIVE on purpose: the container mounts $DEPLOY_PATH at
# /srv, so an absolute host path inside the symlink dangles there and nginx 404s
# on everything.
#
# ln -sfn + mv -T: `ln -sfn` alone would drop the new link *inside* the existing
# `current` directory-symlink instead of replacing it. mv -T is the atomic swap.
echo "==> Switching current -> $TAG"
remote "cd '$DEPLOY_PATH' && ln -sfn 'releases/$TAG' current.tmp && mv -Tf current.tmp current"

echo "==> Pruning old releases (keeping $KEEP_RELEASES)"
remote "cd '$DEPLOY_PATH/releases' && ls -1t | tail -n +$((KEEP_RELEASES + 1)) | xargs -r rm -rf"

echo "Deployed $TAG"

if [[ -n "$conf_changed" ]]; then
    echo
    echo "nginx.conf changed — restart the web service in Coolify to pick it up."
fi
