using System;
using System.Collections.Generic;
using System.Text;

namespace Internal
{
    public static class AudioCatalogClassGenerator
    {
        public const string GeneratedFolder = "Assets/Common/Internal/Runtime/Catalogues/Audio/Generated";

        // Клипы — типы UnityEngine, поэтому классы всех групп лежат в Internal, а не в сборках модулей.
        private const string OwnedSuffix = "Audio.cs";

        private const string LogTag = "AudioCatalogClassGenerator";

        internal static void Generate(IReadOnlyList<AudioGroupDefinition> groups)
        {
            CatalogPaths.EnsureFolder(GeneratedFolder);

            var written = new HashSet<string>(StringComparer.Ordinal);

            foreach (var group in groups)
            {
                var fileName = group.ClassName + ".cs";
                written.Add(fileName);
                GeneratedFile.WriteIfChanged(LogTag, $"{GeneratedFolder}/{fileName}", BuildGroupClass(group));
            }

            GeneratedFile.DeleteStale(LogTag, GeneratedFolder, written, OwnedSuffix);
        }

        private static string BuildGroupClass(AudioGroupDefinition group)
        {
            const string soundType = "global::Internal.Sound";

            var builder = new StringBuilder();
            builder.AppendLine("// Auto-generated by AudioCatalogGenerator. Do not edit manually.");
            builder.AppendLine("using Cysharp.Threading.Tasks;");
            builder.AppendLine("using Unity.Scripting.LifecycleManagement;");
            builder.AppendLine();
            builder.AppendLine("namespace Internal {");
            builder.AppendLine("    [NoAutoStaticsCleanup]");
            builder.AppendLine($"    public static class {group.ClassName} {{");
            builder.AppendLine($"        private const string Address = \"{group.Address}\";");
            builder.AppendLine();

            foreach (var property in group.Properties)
                builder.AppendLine($"        private static {soundType} {property.FieldName};");

            builder.AppendLine();
            builder.AppendLine("        public static AudioGroup Group { get; } = new Loader();");
            builder.AppendLine();
            builder.AppendLine("        public static bool IsLoaded => Group.IsLoaded;");
            builder.AppendLine();

            foreach (var property in group.Properties)
            {
                builder.AppendLine($"        public static {soundType} {property.PropertyName} {{");
                builder.AppendLine($"            get {{ Group.EnsureLoaded(); return {property.FieldName}; }}");
                builder.AppendLine("        }");
                builder.AppendLine();
            }

            builder.AppendLine("        private sealed class Loader : AudioGroup {");
            builder.AppendLine($"            public override string Name => nameof({group.ClassName});");
            builder.AppendLine();
            builder.AppendLine("            protected override async UniTask LoadGroup() {");
            builder.AppendLine("                await LoadAsset(Address);");

            foreach (var property in group.Properties)
                builder.AppendLine($"                {property.FieldName} = Asset.Get(\"{property.PropertyName}\");");

            builder.AppendLine("            }");
            builder.AppendLine();
            builder.AppendLine("            protected override void UnloadGroup() {");

            foreach (var property in group.Properties)
                builder.AppendLine($"                {property.FieldName} = null;");

            builder.AppendLine("                UnloadAsset();");
            builder.AppendLine("            }");
            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine("}");
            return builder.ToString();
        }
    }
}
