FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 9090
EXPOSE 9443

ENV ASPNETCORE_URLS=http://+:9090

ENV ConnectionStrings__postgres=${DB_CONNECTION_STRING}
ENV ConnectionStrings__otel=${OTEL_CONNECTION_STRING}
ENV SERVICE_NAME=GameGateway
ENV SERVICE_PUBLIC_URL=${SERVICE_PUBLIC_URL}

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
ARG BUILD_CONFIGURATION=Release

WORKDIR /src

COPY backend/ .
COPY shared/ .

RUN dotnet restore "Game/Gateway/GameGateway/GameGateway.csproj"

COPY . .
WORKDIR "/src/backend/Game/Gateway/GameGateway"

RUN dotnet build "GameGateway.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "GameGateway.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Game.Gateway.GameGateway.dll"]
