using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ContainerGenerator {
    internal sealed class ManifestHarvest {
        public string Source = "";
        public List<Mapping> Mappings = new List<Mapping>();

        public sealed class Mapping {
            public string HarvestName = "";
            public string OriginalId = "";
        }

        public static ManifestHarvest? TryBuild(Compilation compilation, ReferenceSymbols references) {
            if (references.GraphRootAttribute == null)
                return null;

            var harvest = new ManifestHarvest();
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine("#pragma warning disable");
            builder.AppendLine("using System;");
            var blocks = new List<string>();
            var serial = 0;

            foreach (var type in compilation.Assembly.GlobalNamespace.GetAllTypes()) {
                foreach (var member in type.GetMembers()) {
                    if (member is not IMethodSymbol method)
                        continue;
                    if (method.IsStatic == false)
                        continue;
                    if (method.MethodKind != MethodKind.Ordinary)
                        continue;
                    if (HasBuilderParameter(method, references) == false)
                        continue;
                    if (method.DeclaringSyntaxReferences.Length == 0)
                        continue;
                    if (method.Name == "Construct" || method.Name == "Build")
                        continue;
                    if (method.IsGenericMethod || method.TypeParameters.Length > 0)
                        continue;

                    var syntax = method.DeclaringSyntaxReferences[0].GetSyntax() as MethodDeclarationSyntax;
                    if (syntax == null)
                        continue;

                    var ns = type.ContainingNamespace == null || type.ContainingNamespace.IsGlobalNamespace
                        ? ""
                        : type.ContainingNamespace.ToDisplayString();
                    var harvestName = "H" + serial.ToString();
                    serial++;
                    var harvestType = "ContainerInstallerHarvest" + serial.ToString();
                    harvest.Mappings.Add(new Mapping {
                        HarvestName = harvestName,
                        OriginalId = MethodIds.Of(method),
                    });

                    var block = new StringBuilder();
                    if (string.IsNullOrEmpty(ns) == false)
                        block.AppendLine("namespace " + ns + " {");
                    else
                        block.AppendLine("namespace ContainerInstallerHarvestGlobal {");
                    AppendUsings(syntax, block);
                    block.AppendLine("    public static class " + harvestType + " {");
                    block.AppendLine("        [global::Internal.ContainerGraphRoot]");
                    block.Append("        public static void " + harvestName + "(");
                    block.Append(Parameters(method));
                    block.AppendLine(") {");
                    block.Append(Inline(syntax));
                    block.AppendLine("        }");
                    block.AppendLine("    }");
                    block.AppendLine("}");
                    blocks.Add(block.ToString());
                }
            }

            if (harvest.Mappings.Count == 0)
                return null;

            builder.AppendLine();
            for (var i = 0; i < blocks.Count; i++)
                builder.AppendLine(blocks[i]);

            harvest.Source = builder.ToString();
            return harvest;
        }

        public static void Remap(GraphDocument document, ManifestHarvest? harvest) {
            if (document == null || harvest == null)
                return;

            var byId = new Dictionary<string, GraphMethod>(StringComparer.Ordinal);
            for (var i = 0; i < document.Methods.Count; i++)
                byId[document.Methods[i].Id] = document.Methods[i];

            var remove = new HashSet<string>(StringComparer.Ordinal);
            for (var i = 0; i < harvest.Mappings.Count; i++) {
                var mapping = harvest.Mappings[i];
                var harvested = FindHarvest(document, mapping.HarvestName);
                if (harvested == null)
                    continue;

                remove.Add(harvested.Id);
                if (byId.TryGetValue(mapping.OriginalId, out var original)) {
                    // Копия с инлайном локальных функций видит больше обхода оригинала — тогда тело метода берётся из неё
                    // целиком. Слияние теряло повторные дженерик-вызовы (RegisterCommand<A>, <B>) и вызовы без регистраций.
                    if (Size(harvested) > Size(original))
                        ReplaceBody(original, harvested);

                    continue;
                }

                var copy = new GraphMethod {
                    Id = mapping.OriginalId,
                    IsRoot = false,
                    File = harvested.File,
                    Line = harvested.Line,
                    AssemblyName = document.AssemblyName,
                };
                ReplaceBody(copy, harvested);
                document.Methods.Add(copy);
                byId[copy.Id] = copy;
            }

            if (remove.Count == 0)
                return;

            document.Methods.RemoveAll(method => remove.Contains(method.Id) || ScopePlan.IsHarvest(method.Id));
        }

        private static GraphMethod? FindHarvest(GraphDocument document, string harvestName) {
            var suffix = "." + harvestName;
            for (var i = 0; i < document.Methods.Count; i++) {
                var method = document.Methods[i];
                if (ScopePlan.IsHarvest(method.Id) == false)
                    continue;
                if (method.Id.EndsWith(suffix, StringComparison.Ordinal))
                    return method;
            }

            return null;
        }

        private static List<GraphRegistration> CloneRegistrations(GraphMethod method) {
            var list = new List<GraphRegistration>();
            for (var i = 0; i < method.Registrations.Count; i++)
                list.Add(method.Registrations[i].Clone());
            return list;
        }

        private static int Size(GraphMethod method) {
            return method.Registrations.Count + method.Calls.Count;
        }

        private static void ReplaceBody(GraphMethod target, GraphMethod harvested) {
            harvested.PadCallLists();
            target.Registrations.Clear();
            target.Registrations.AddRange(CloneRegistrations(harvested));
            target.Calls.Clear();
            target.CallOrdinals.Clear();
            target.CallTypeArguments.Clear();
            target.CallAsServices.Clear();
            target.CallHoles.Clear();
            target.Calls.AddRange(harvested.Calls);
            target.CallOrdinals.AddRange(harvested.CallOrdinals);
            target.CallTypeArguments.AddRange(harvested.CallTypeArguments);
            target.CallAsServices.AddRange(harvested.CallAsServices);
            target.CallHoles.AddRange(harvested.CallHoles);
            target.ReturnedOrdinal = harvested.ReturnedOrdinal;
        }

        private static bool HasBuilderParameter(IMethodSymbol method, ReferenceSymbols references) {
            foreach (var parameter in method.Parameters) {
                var type = parameter.Type;
                if (type.Name == "IBuilder" || type.Name == "IScopeBuilder" || type.Name == "IEntityBuilder")
                    return true;
                if (type.Implements(references.Builder) || type.Implements(references.ScopeBuilder) || type.Implements(references.EntityBuilder))
                    return true;
            }

            return false;
        }

        // Копия тела резолвится в том же окружении, что оригинал: using'и файла и объемлющих
        // namespace. Внутри namespace-блока пишутся через global::, чтобы не цеплять вложенные имена.
        private static void AppendUsings(MethodDeclarationSyntax method, StringBuilder block) {
            var directives = new List<UsingDirectiveSyntax>();
            if (method.SyntaxTree.GetRoot() is CompilationUnitSyntax unit)
                directives.AddRange(unit.Usings);
            foreach (var ancestor in method.Ancestors()) {
                if (ancestor is NamespaceDeclarationSyntax declaration)
                    directives.AddRange(declaration.Usings);
            }

            var seen = new HashSet<string>(StringComparer.Ordinal);
            foreach (var directive in directives) {
                var name = directive.Name.ToString();
                if (name.StartsWith("global::", StringComparison.Ordinal) == false)
                    name = "global::" + name;

                var text = "    using " +
                           (directive.StaticKeyword.IsKind(SyntaxKind.None) ? "" : "static ") +
                           (directive.Alias == null ? "" : directive.Alias.Name.ToString() + " = ") +
                           name + ";";
                if (seen.Add(text))
                    block.AppendLine(text);
            }
        }

        private static string Parameters(IMethodSymbol method) {
            var parts = new List<string>();
            for (var i = 0; i < method.Parameters.Length; i++) {
                var parameter = method.Parameters[i];
                parts.Add(TypeNames.ForCode(parameter.Type) + " " + ScopeNames.Escape(parameter.Name));
            }

            return string.Join(", ", parts);
        }

        private static string Inline(MethodDeclarationSyntax method) {
            if (method.Body == null) {
                if (method.ExpressionBody != null)
                    return "            " + method.ExpressionBody.Expression.ToString() + ";\n";
                return "";
            }

            var locals = new Dictionary<string, LocalFunctionStatementSyntax>(StringComparer.Ordinal);
            foreach (var local in method.Body.DescendantNodes()) {
                if (local is LocalFunctionStatementSyntax function)
                    locals[function.Identifier.Text] = function;
            }

            var builder = new StringBuilder();
            WriteStatements(method.Body.Statements, locals, builder, new HashSet<string>(StringComparer.Ordinal));
            return builder.ToString();
        }

        private static void WriteStatements(
            SyntaxList<StatementSyntax> statements,
            Dictionary<string, LocalFunctionStatementSyntax> locals,
            StringBuilder builder,
            HashSet<string> visiting) {
            foreach (var statement in statements) {
                if (statement is LocalFunctionStatementSyntax)
                    continue;

                if (TryLocalInvocation(statement, locals, out var name)) {
                    if (visiting.Add(name) == false)
                        continue;
                    var local = locals[name];
                    if (local.Body != null)
                        WriteStatements(local.Body.Statements, locals, builder, visiting);
                    else if (local.ExpressionBody != null)
                        builder.AppendLine("            " + local.ExpressionBody.Expression.ToString() + ";");
                    visiting.Remove(name);
                    continue;
                }

                builder.AppendLine("            " + statement.ToString());
            }
        }

        private static bool TryLocalInvocation(
            StatementSyntax statement,
            Dictionary<string, LocalFunctionStatementSyntax> locals,
            out string name) {
            name = "";
            if (statement is not ExpressionStatementSyntax expression)
                return false;
            if (expression.Expression is not InvocationExpressionSyntax invocation)
                return false;
            if (invocation.Expression is not IdentifierNameSyntax identifier)
                return false;
            name = identifier.Identifier.Text;
            return locals.ContainsKey(name);
        }
    }
}
