using System;
using System.Collections.Generic;
using Microsoft.CodeAnalysis;

namespace ContainerGenerator {
    internal static class ScopeEmitter {
        public static bool TryEmit(
            ScopeGraph graph,
            GraphDocument document,
            Compilation compilation,
            ReferenceSymbols references,
            out string hintName,
            out string source) {
            hintName = "";
            source = "";
            var plan = ScopePlan.Build(graph, document, compilation, references);
            if (plan == null)
                return false;

            hintName = plan.HintName;
            source = Write(plan, graph);
            return string.IsNullOrEmpty(source) == false;
        }

        private static string Write(ScopePlan plan, ScopeGraph graph) {
            var writer = new CodeWriter();
            writer.AppendLine("// <auto-generated/>");
            writer.AppendLine("#pragma warning disable");
            writer.AppendLine();

            var bases = "global::Internal.IContainer";
            for (var i = 0; i < plan.Provides.Count; i++)
                bases += ", global::Internal.IProvides<" + plan.Provides[i].TargetType + ">";

            if (string.IsNullOrEmpty(plan.Namespace) == false) {
                writer.AppendLine("namespace " + plan.Namespace + " {");
                WriteClass(writer, plan, graph, bases, "    ");
                writer.AppendLine("}");
            }
            else {
                WriteClass(writer, plan, graph, bases, "");
            }

            return writer.ToString();
        }

        private static void WriteClass(
            CodeWriter writer,
            ScopePlan plan,
            ScopeGraph graph,
            string bases,
            string indent) {
            var deeper = indent + "    ";
            var body = indent + "        ";
            writer.AppendLine(indent + "internal sealed class " + plan.ClassName + " : " + bases + " {");
            WriteConstructor(writer, plan, graph, deeper, body);
            writer.AppendLine();
            WriteFields(writer, plan, deeper);
            writer.AppendLine();
            WriteContainerApi(writer, plan, graph, deeper, body);
            WriteRegister(writer, plan, deeper, body);
            WriteFactories(writer, plan, graph, deeper, body);
            WriteProvides(writer, plan, graph, deeper, body);
            WriteDiagnostics(writer, plan, graph, deeper, body);
            writer.AppendLine(indent + "}");
        }

        private static void WriteConstructor(
            CodeWriter writer,
            ScopePlan plan,
            ScopeGraph graph,
            string indent,
            string body) {
            writer.AppendLine(indent + "public " + plan.ClassName + "(");
            for (var i = 0; i < plan.CtorParams.Count; i++) {
                var param = plan.CtorParams[i];
                var comma = i + 1 < plan.CtorParams.Count ? "," : "";
                writer.AppendLine(body + param.Type + " " + param.Name + comma);
            }

            writer.AppendLine(indent + ") {");

            for (var i = 0; i < plan.CtorParams.Count; i++) {
                var param = plan.CtorParams[i];
                if (param.IsLifetime)
                    writer.AppendLine(body + plan.LifetimeField + " = " + param.Name + ";");
                else if (param.IsParent)
                    writer.AppendLine(body + plan.ParentField + " = " + param.Name + ";");
                else if (param.IsAlternative || param.IsRequest)
                    continue;
                else if (string.IsNullOrEmpty(param.FieldName) == false)
                    writer.AppendLine(body + param.FieldName + " = " + param.Name + ";");
                else if (param.Slot >= 0 && param.Slot < plan.Slots.Count) {
                    var slot = plan.Slots[param.Slot];
                    if (slot.IsHole && string.IsNullOrEmpty(slot.FieldName) == false)
                        writer.AppendLine(body + slot.FieldName + " = " + param.Name + ";");
                }
            }

            var constructed = new HashSet<int>();
            for (var o = 0; o < graph.ConstructionOrder.Count; o++) {
                var index = graph.ConstructionOrder[o];
                if (index < 0 || index >= plan.Slots.Count)
                    continue;
                WriteSlotConstruction(writer, plan, graph, index, body, constructed);
            }

            for (var i = 0; i < plan.Slots.Count; i++) {
                if (constructed.Contains(i) == false)
                    WriteSlotConstruction(writer, plan, graph, i, body, constructed);
            }

            WriteMarkers(writer, plan, graph, body);
            if (plan.HasContainerDiagnostics) {
                // Диагностика есть только в редакторе и dev-билде; бенчмарк выключает её флагом.
                writer.AppendLine("#if UNITY_EDITOR || DEBUG");
                writer.AppendLine(body + "if (global::Internal.ContainerRegistryDebug.IsEnabled == true) {");
                writer.AppendLine(body + "    _diagnostics = new global::Internal.ContainerDiagnostics(");
                writer.AppendLine(body + "        " + Literal(plan.ClassName) + ",");
                writer.AppendLine(body + "        " + plan.ParentField + " != null ? " + plan.ParentField + ".Diagnostics : null,");
                writer.AppendLine(body + "        _registrationInfos,");
                writer.AppendLine(body + "        _buildOrder);");
                writer.AppendLine(body + "}");
                writer.AppendLine("#endif");
            }

            writer.AppendLine(indent + "}");
        }

        private static void WriteSlotConstruction(
            CodeWriter writer,
            ScopePlan plan,
            ScopeGraph graph,
            int index,
            string indent,
            HashSet<int> constructed) {
            if (constructed.Add(index) == false)
                return;

            var slot = plan.Slots[index];
            if (slot.SkipEmit || slot.IsTransient)
                return;
            if (slot.IsSwitch) {
                WriteSwitchConstruction(writer, plan, graph, slot, indent);
                return;
            }
            if (slot.IsAlternative && slot.IsGroupPrimary == false)
                return;

            if (slot.IsHole) {
                WriteConstructCall(writer, plan, graph, slot, slot.FieldName, indent);
                return;
            }

            if (slot.IsAlternative && slot.IsGroupPrimary) {
                WriteAlternative(writer, plan, graph, slot, indent);
                WriteConstructCall(writer, plan, graph, slot, slot.FieldName, indent);
                return;
            }

            if (string.IsNullOrEmpty(slot.FieldName) || string.IsNullOrEmpty(slot.ImplementationType))
                return;

            writer.AppendLine(indent + slot.FieldName + " = " +
                              NewExpression(plan, graph, slot.ImplementationType, slot.Registration, "Constructor") + ";");
            WriteConstructCall(writer, plan, graph, slot, slot.FieldName, indent);
        }

        // Синглтон ветки switch: поле, построенное по значению дискриминанта в скоупе (locked 8).
        private static void WriteSwitchConstruction(
            CodeWriter writer,
            ScopePlan plan,
            ScopeGraph graph,
            ScopePlan.Slot slot,
            string indent) {
            GraphEdge? discriminant = null;
            for (var i = 0; i < slot.Registration.Dependencies.Count; i++) {
                if (slot.Registration.Dependencies[i].Source == "Discriminant")
                    discriminant = slot.Registration.Dependencies[i];
            }

            if (discriminant == null || string.IsNullOrEmpty(slot.FieldName))
                throw new InvalidOperationException("Generator switch '" + slot.CreateMethod + "' has no discriminant.");

            writer.AppendLine(indent + slot.FieldName + " = " + slot.CreateMethod + "(" +
                              Argument(plan, graph, discriminant) +
                              (plan.NeedsRequest ? ", request" : "") + ");");
        }

        private static void WriteAlternative(
            CodeWriter writer,
            ScopePlan plan,
            ScopeGraph graph,
            ScopePlan.Slot slot,
            string indent) {
            // Ветка if/switch в installer'е выполнилась одна: строится та реализация, что попала в билдер.
            var members = slot.GroupMembers.Count == 0 ? new List<int> { slot.Index } : slot.GroupMembers;
            writer.AppendLine(indent + slot.FieldName + " =");
            for (var m = 0; m < members.Count; m++) {
                var member = plan.Slots[members[m]];
                writer.AppendLine(indent + "    request.IsRegistered(typeof(" + member.ImplementationType + "))");
                writer.AppendLine(indent + "        ? (" + slot.FieldType + ")" +
                                  NewExpression(plan, graph, member.ImplementationType, member.Registration, "Constructor"));
                writer.AppendLine(indent + "        :");
            }

            writer.AppendLine(indent + "    throw new global::System.InvalidOperationException(\"No alternative of " +
                              ScopeNames.StripGlobal(slot.FieldType) + " was registered.\");");
        }

        private static void WriteConstructCall(
            CodeWriter writer,
            ScopePlan plan,
            ScopeGraph graph,
            ScopePlan.Slot slot,
            string target,
            string indent) {
            if (string.IsNullOrEmpty(target))
                return;

            var args = Arguments(plan, graph, slot.Registration, "Construct");
            if (args == null)
                return;
            var method = ConstructName(slot.Registration);
            if (args.Count == 0)
                writer.AppendLine(indent + target + "." + method + "();");
            else
                writer.AppendLine(indent + target + "." + method + "(" + string.Join(", ", args) + ");");
        }

        // Имя метода с [Inject] лежит на рёбрах Source == "Construct"; без рёбер вызова нет.
        private static string ConstructName(GraphRegistration registration, int arm = -1) {
            for (var i = 0; i < registration.Dependencies.Count; i++) {
                var edge = registration.Dependencies[i];
                if (edge.Source != "Construct" || edge.Arm != arm)
                    continue;
                if (string.IsNullOrEmpty(edge.Method) == false)
                    return edge.Method;
            }

            if (arm < 0 && string.IsNullOrEmpty(registration.InjectMethod) == false)
                return registration.InjectMethod;
            return "Construct";
        }

        private static string NewExpression(
            ScopePlan plan,
            ScopeGraph graph,
            string type,
            GraphRegistration registration,
            string source,
            int arm = -1) {
            var args = Arguments(plan, graph, registration, source, arm);
            if (args == null || args.Count == 0)
                return "new " + type + "()";
            return "new " + type + "(" + string.Join(", ", args) + ")";
        }

        private static List<string>? Arguments(
            ScopePlan plan,
            ScopeGraph graph,
            GraphRegistration registration,
            string source,
            int arm = -1) {
            var found = false;
            var args = new List<string>();
            for (var i = 0; i < registration.Dependencies.Count; i++) {
                var edge = registration.Dependencies[i];
                if (edge.Source != source)
                    continue;
                if (edge.Arm != arm)
                    continue;
                found = true;
                args.Add(Argument(plan, graph, edge));
            }

            // [Inject] без параметров рёбер не даёт, но вызывается.
            if (found == false)
                return source == "Construct" && (arm >= 0 || string.IsNullOrEmpty(registration.InjectMethod)) ? null : args;
            return args;
        }

        private static string Argument(ScopePlan plan, ScopeGraph graph, GraphEdge edge) {
            if (edge.Kind == "Implicit") {
                if (IsContainerType(edge.ParameterType))
                    return "this";
                return plan.LifetimeField;
            }

            if (edge.Kind == "ArmParameter")
                return "request.Get<" + edge.ParameterType + ">()";

            if (edge.Kind == "Hole")
                return HoleParam(plan, edge);

            if (edge.Kind == "Collection")
                return CollectionExpression(plan, graph, edge);

            if (edge.Kind == "Registration" && edge.TargetIndex >= 0 && edge.TargetIndex < plan.Slots.Count) {
                var target = plan.Slots[edge.TargetIndex];
                if (target.IsTransient && string.IsNullOrEmpty(target.CreateMethod) == false)
                    return target.CreateMethod + "()";
                if (string.IsNullOrEmpty(target.FieldName) == false)
                    return target.FieldName;
            }

            throw new InvalidOperationException(
                "Generator cannot emit argument for '" + edge.ParameterName + "' of type '" + edge.ParameterType + "'.");
        }

        private static string CollectionExpression(ScopePlan plan, ScopeGraph graph, GraphEdge edge) {
            var element = edge.ParameterType;
            if (element.EndsWith("[]", StringComparison.Ordinal))
                element = element.Substring(0, element.Length - 2);
            else
                TryUnwrapList(edge.ParameterType, out element);

            var items = new List<string>();
            for (var i = 0; i < edge.CollectionIndices.Count; i++) {
                var index = edge.CollectionIndices[i];
                if (index < 0 || index >= plan.Slots.Count)
                    continue;
                var slot = plan.Slots[index];
                if (slot.IsTransient && string.IsNullOrEmpty(slot.CreateMethod) == false)
                    items.Add(slot.CreateMethod + "()");
                else if (string.IsNullOrEmpty(slot.FieldName) == false)
                    items.Add(slot.FieldName);
            }

            return "new " + element + "[] { " + string.Join(", ", items) + " }";
        }

        private static string HoleParam(ScopePlan plan, GraphEdge edge) {
            for (var i = 0; i < plan.CtorParams.Count; i++) {
                var param = plan.CtorParams[i];
                if (param.IsLifetime || param.IsParent || param.IsRequest || param.IsAlternative)
                    continue;
                if (param.Type == edge.ParameterType &&
                    (param.Name == edge.ParameterName || param.Name == ScopeNames.Escape(edge.ParameterName)))
                    return HoleValue(plan, param);
            }

            for (var i = 0; i < plan.CtorParams.Count; i++) {
                var param = plan.CtorParams[i];
                if (param.IsLifetime || param.IsParent || param.IsRequest || param.IsAlternative)
                    continue;
                if (param.Type == edge.ParameterType)
                    return HoleValue(plan, param);
            }

            throw new InvalidOperationException(
                "Generator hole '" + edge.ParameterName + "' of type '" + edge.ParameterType +
                "' has no constructor parameter.");
        }

        // Значение дырки доступно везде в классе: поле ребра или поле слота, не параметр конструктора.
        private static string HoleValue(ScopePlan plan, ScopePlan.CtorParam param) {
            if (string.IsNullOrEmpty(param.FieldName) == false)
                return param.FieldName;
            if (param.Slot >= 0 && param.Slot < plan.Slots.Count &&
                string.IsNullOrEmpty(plan.Slots[param.Slot].FieldName) == false)
                return plan.Slots[param.Slot].FieldName;
            return param.Name;
        }

        private static string AlternativeParam(ScopePlan plan, int group) {
            for (var i = 0; i < plan.CtorParams.Count; i++) {
                if (plan.CtorParams[i].IsAlternative && plan.CtorParams[i].AlternativeGroup == group)
                    return plan.CtorParams[i].Name;
            }

            return "";
        }

        private static void WriteMarkers(CodeWriter writer, ScopePlan plan, ScopeGraph graph, string indent) {
            for (var i = 0; i < plan.Markers.Count; i++) {
                var marker = plan.Markers[i];
                // Список с transient'ами собирается на каждый ResolveAll: поле держало бы одни и те же экземпляры.
                if (ScopePlan.HasTransientSlot(plan, marker.Slots))
                    continue;

                writer.AppendLine(indent + marker.FieldName + " = " + MarkerArray(plan, i) + ";");
            }
        }

        private static string MarkerArray(ScopePlan plan, int markerIndex) {
            var marker = plan.Markers[markerIndex];
            var items = new List<string>();
            var seen = new HashSet<string>(StringComparer.Ordinal);
            for (var s = 0; s < marker.Slots.Count; s++) {
                var slot = plan.Slots[marker.Slots[s]];
                if (slot.IsTransient) {
                    if (string.IsNullOrEmpty(slot.CreateMethod) == false)
                        items.Add(slot.CreateMethod + "()");
                    continue;
                }

                if (string.IsNullOrEmpty(slot.FieldName))
                    continue;
                if (seen.Add(slot.FieldName) == false)
                    continue;
                items.Add(slot.FieldName);
            }

            return "new " + marker.ElementType + "[] { " + string.Join(", ", items) + " }";
        }

        // Тип → номер экземпляра в GetExport. Таблица статическая, общая для всех экземпляров класса:
        // экземпляры и так лежат в полях, и скоуп не платит за свой словарь (340–790 байт).
        private static void WriteExportTable(CodeWriter writer, ScopePlan plan, string indent) {
            var values = ExportValues(plan);
            writer.AppendLine(indent + "private static readonly global::System.Collections.Generic.Dictionary<global::System.Type, int> _exports =");
            writer.AppendLine(indent + "    new global::System.Collections.Generic.Dictionary<global::System.Type, int>(" +
                              plan.Exports.Count.ToString() + ") {");
            for (var i = 0; i < plan.Exports.Count; i++) {
                var export = plan.Exports[i];
                var index = values.IndexOf(ExportValue(plan, export.Slot));
                var comma = i + 1 < plan.Exports.Count ? "," : "";
                writer.AppendLine(indent + "        { typeof(" + export.ServiceType + "), " + index.ToString() + " }" + comma);
            }

            writer.AppendLine(indent + "    };");
        }

        private static void WriteGetExport(CodeWriter writer, ScopePlan plan, string indent, string body) {
            var values = ExportValues(plan);
            writer.AppendLine(indent + "private object GetExport(int index) {");
            writer.AppendLine(body + "switch (index) {");
            for (var i = 0; i < values.Count; i++)
                writer.AppendLine(body + "    case " + i.ToString() + ": return " + values[i] + ";");
            writer.AppendLine(body + "    default: return null;");
            writer.AppendLine(body + "}");
            writer.AppendLine(indent + "}");
            writer.AppendLine();
        }

        // Несколько сервисных типов одного экземпляра делят один case.
        private static List<string> ExportValues(ScopePlan plan) {
            var values = new List<string>();
            for (var i = 0; i < plan.Exports.Count; i++) {
                var value = ExportValue(plan, plan.Exports[i].Slot);
                if (values.Contains(value) == false)
                    values.Add(value);
            }

            return values;
        }

        private static string ExportValue(ScopePlan plan, int slotIndex) {
            var slot = plan.Slots[slotIndex];
            return string.IsNullOrEmpty(slot.FieldName) ? "this" : slot.FieldName;
        }

        private static void WriteFields(CodeWriter writer, ScopePlan plan, string indent) {
            for (var i = 0; i < plan.Fields.Count; i++) {
                var field = plan.Fields[i];
                writer.AppendLine(indent + "private readonly " + field.Type + " " + field.Name + ";");
            }

            WriteExportTable(writer, plan, indent);
            if (plan.HasContainerDiagnostics)
                writer.AppendLine(indent + "private readonly global::Internal.ContainerDiagnostics _diagnostics;");
            writer.AppendLine(indent + "private bool _disposed;");
        }

        private static void WriteContainerApi(
            CodeWriter writer,
            ScopePlan plan,
            ScopeGraph graph,
            string indent,
            string body) {
            if (plan.HasDiagnosticsType) {
                var diagnostics = plan.HasContainerDiagnostics ? "_diagnostics" : "null";
                writer.AppendLine(indent + "public global::Internal.IContainerDiagnostics Diagnostics => " + diagnostics + ";");
                writer.AppendLine();
            }

            writer.AppendLine(indent + "public global::Internal.IReadOnlyLifetime Lifetime => " + plan.LifetimeField + ";");
            writer.AppendLine();
            writer.AppendLine(indent + "public object Resolve(global::System.Type type) {");
            writer.AppendLine(body + "if (_exports.TryGetValue(type, out var export) == true)");
            writer.AppendLine(body + "    return GetExport(export);");
            WriteTransientResolve(writer, plan, body, false);
            writer.AppendLine(body + "if (" + plan.ParentField + " != null)");
            writer.AppendLine(body + "    return " + plan.ParentField + ".Resolve(type);");
            writer.AppendLine(body + "throw new global::System.InvalidOperationException(\"No registration for type \" + type.FullName + \".\");");
            writer.AppendLine(indent + "}");
            writer.AppendLine();
            writer.AppendLine(indent + "public T Resolve<T>() {");
            writer.AppendLine(body + "return (T)Resolve(typeof(T));");
            writer.AppendLine(indent + "}");
            writer.AppendLine();
            writer.AppendLine(indent + "public bool TryResolve(global::System.Type type, out object instance) {");
            writer.AppendLine(body + "if (type == null) {");
            writer.AppendLine(body + "    instance = null;");
            writer.AppendLine(body + "    return false;");
            writer.AppendLine(body + "}");
            writer.AppendLine(body + "if (_exports.TryGetValue(type, out var export) == true) {");
            writer.AppendLine(body + "    instance = GetExport(export);");
            writer.AppendLine(body + "    return true;");
            writer.AppendLine(body + "}");
            WriteTransientResolve(writer, plan, body, true);
            writer.AppendLine(body + "if (" + plan.ParentField + " != null)");
            writer.AppendLine(body + "    return " + plan.ParentField + ".TryResolve(type, out instance);");
            writer.AppendLine(body + "instance = null;");
            writer.AppendLine(body + "return false;");
            writer.AppendLine(indent + "}");
            writer.AppendLine();
            WriteGetExport(writer, plan, indent, body);
            WriteResolveAll(writer, plan, indent, body);
            writer.AppendLine(indent + "public void Inject(object target) {");
            writer.AppendLine(body + "if (target == null)");
            writer.AppendLine(body + "    throw new global::System.ArgumentNullException(nameof(target));");
            WriteInjectCases(writer, plan, graph, body);
            writer.AppendLine(body + "throw new global::System.InvalidOperationException(\"No generated inject for \" + target.GetType().FullName + \".\");");
            writer.AppendLine(indent + "}");
            writer.AppendLine();
            if (plan.HasUnityGameObject) {
                writer.AppendLine(indent + "public void InjectGameObject(global::UnityEngine.GameObject target) {");
                writer.AppendLine(body + "if (target == null)");
                writer.AppendLine(body + "    throw new global::System.ArgumentNullException(nameof(target));");
                writer.AppendLine(body + "var behaviours = target.GetComponentsInChildren<global::UnityEngine.MonoBehaviour>(true);");
                writer.AppendLine(body + "for (var i = 0; i < behaviours.Length; i++) {");
                writer.AppendLine(body + "    var behaviour = behaviours[i];");
                writer.AppendLine(body + "    if (behaviour == null)");
                writer.AppendLine(body + "        continue;");
                writer.AppendLine(body + "    Inject(behaviour);");
                writer.AppendLine(body + "}");
                writer.AppendLine(indent + "}");
                writer.AppendLine();
            }
            else {
                writer.AppendLine(indent + "public void InjectGameObject(object target) {");
                writer.AppendLine(body + "Inject(target);");
                writer.AppendLine(indent + "}");
                writer.AppendLine();
            }

            writer.AppendLine(indent + "public void Dispose() {");
            writer.AppendLine(body + "if (_disposed == true)");
            writer.AppendLine(body + "    return;");
            writer.AppendLine(body + "_disposed = true;");
            for (var i = 0; i < plan.DisposeOrder.Count; i++) {
                var slot = plan.Slots[plan.DisposeOrder[i]];
                if (string.IsNullOrEmpty(slot.FieldName) == false)
                    writer.AppendLine(body + "((global::System.IDisposable)" + slot.FieldName + ").Dispose();");
            }

            writer.AppendLine(body + plan.LifetimeField + ".Terminate();");
            writer.AppendLine(indent + "}");
            writer.AppendLine();
        }

        private static void WriteTransientResolve(CodeWriter writer, ScopePlan plan, string indent, bool assign) {
            // Одному типу — одна ветка. Как и в _exports, резолв отдаёт последнюю регистрацию,
            // а экспорт синглтона того же типа проверяется раньше и ветку не получает.
            var exported = new HashSet<string>(StringComparer.Ordinal);
            for (var i = 0; i < plan.Exports.Count; i++)
                exported.Add(plan.Exports[i].ServiceType);

            var owners = new Dictionary<string, int>(StringComparer.Ordinal);
            for (var i = 0; i < plan.Slots.Count; i++) {
                foreach (var type in TransientTypes(plan, i)) {
                    if (exported.Contains(type) == false)
                        owners[type] = i;
                }
            }

            for (var i = 0; i < plan.Slots.Count; i++) {
                var slot = plan.Slots[i];
                var types = TransientTypes(plan, i);
                for (var t = 0; t < types.Count; t++) {
                    if (owners.TryGetValue(types[t], out var owner) == false || owner != i)
                        continue;
                    writer.AppendLine(indent + "if (type == typeof(" + types[t] + ")) {");
                    if (assign) {
                        writer.AppendLine(indent + "    instance = " + slot.CreateMethod + "();");
                        writer.AppendLine(indent + "    return true;");
                    }
                    else {
                        writer.AppendLine(indent + "    return " + slot.CreateMethod + "();");
                    }

                    writer.AppendLine(indent + "}");
                }
            }
        }

        private static List<string> TransientTypes(ScopePlan plan, int slotIndex) {
            var types = new List<string>();
            var slot = plan.Slots[slotIndex];
            if (slot.IsTransient == false || string.IsNullOrEmpty(slot.CreateMethod))
                return types;
            if (string.IsNullOrEmpty(slot.ImplementationType) == false)
                types.Add(slot.ImplementationType);
            for (var s = 0; s < slot.Registration.ServiceTypes.Count; s++) {
                var service = slot.Registration.ServiceTypes[s];
                if (string.IsNullOrEmpty(service) == false && types.Contains(service) == false)
                    types.Add(service);
            }

            return types;
        }

        private static void WriteResolveAll(CodeWriter writer, ScopePlan plan, string indent, string body) {
            writer.AppendLine(indent + "public global::System.Collections.Generic.IReadOnlyList<T> ResolveAll<T>() {");
            for (var i = 0; i < plan.Markers.Count; i++) {
                var marker = plan.Markers[i];
                var list = ScopePlan.HasTransientSlot(plan, marker.Slots) ? MarkerArray(plan, i) : marker.FieldName;
                writer.AppendLine(body + "if (typeof(T) == typeof(" + marker.ElementType + "))");
                writer.AppendLine(body + "    return (global::System.Collections.Generic.IReadOnlyList<T>)(object)" + list + ";");
            }

            // Тип с единственной регистрацией маркерного массива не получает.
            writer.AppendLine(body + "if (_exports.TryGetValue(typeof(T), out var single) == true)");
            writer.AppendLine(body + "    return new T[] { (T)GetExport(single) };");
            writer.AppendLine(body + "return global::System.Array.Empty<T>();");
            writer.AppendLine(indent + "}");
            writer.AppendLine();
        }

        private static void WriteInjectCases(
            CodeWriter writer,
            ScopePlan plan,
            ScopeGraph graph,
            string indent) {
            var used = new HashSet<string>(StringComparer.Ordinal);
            var seen = new HashSet<string>(StringComparer.Ordinal);
            for (var i = 0; i < plan.Slots.Count; i++) {
                var slot = plan.Slots[i];
                if (string.IsNullOrEmpty(slot.ImplementationType))
                    continue;
                if (seen.Add(slot.ImplementationType) == false)
                    continue;
                var args = Arguments(plan, graph, slot.Registration, "Construct");
                if (args == null)
                    continue;

                var local = ScopeNames.Unique(ScopeNames.Camel(ScopeNames.Short(slot.ImplementationType)), used);
                var method = ConstructName(slot.Registration);
                writer.AppendLine(indent + "if (target is " + slot.ImplementationType + " " + local + ") {");
                if (args.Count == 0)
                    writer.AppendLine(indent + "    " + local + "." + method + "();");
                else
                    writer.AppendLine(indent + "    " + local + "." + method + "(" + string.Join(", ", args) + ");");
                writer.AppendLine(indent + "    return;");
                writer.AppendLine(indent + "}");
            }
        }

        private static void WriteRegister(
            CodeWriter writer,
            ScopePlan plan,
            string indent,
            string body) {
            if (plan.HasRuntimeInitialize)
                writer.AppendLine(indent + "[global::UnityEngine.RuntimeInitializeOnLoadMethod(global::UnityEngine.RuntimeInitializeLoadType.SubsystemRegistration)]");

            writer.AppendLine(indent + "private static void RegisterGenerated() {");
            if (string.IsNullOrEmpty(plan.ViewType) == false && plan.OriginRootId != plan.RootId) {
                // Вариант сущности: загрузчик ищет класс по корню и конкретному типу вьюхи.
                writer.AppendLine(body + "global::Internal.GeneratedScopes.RegisterVariant(");
                writer.AppendLine(body + "    " + Literal(plan.OriginRootId) + ",");
                writer.AppendLine(body + "    typeof(global::" + ScopeNames.StripGlobal(plan.ViewType) + "),");
            }
            else {
                writer.AppendLine(body + "global::Internal.GeneratedScopes.Register(");
                writer.AppendLine(body + "    " + Literal(plan.RootId) + ",");
            }

            writer.AppendLine(body + "    request => new " + plan.ClassName + "(");
            for (var i = 0; i < plan.CtorParams.Count; i++) {
                var param = plan.CtorParams[i];
                var argument = param.IsLifetime
                    ? "request.Lifetime"
                    : param.IsParent
                        ? "request.Parent"
                        : param.IsRequest
                            ? "request"
                            : "request.Get<" + param.Type + ">()";
                var comma = i + 1 < plan.CtorParams.Count ? "," : "";
                writer.AppendLine(body + "        " + argument + comma);
            }

            writer.AppendLine(body + "    ));");
            writer.AppendLine(indent + "}");
            writer.AppendLine();
        }

        private static string Literal(string value) {
            if (value == null)
                value = "";
            return "@\"" + value.Replace("\"", "\"\"") + "\"";
        }

        private static void WriteFactories(
            CodeWriter writer,
            ScopePlan plan,
            ScopeGraph graph,
            string indent,
            string body) {
            for (var i = 0; i < plan.Slots.Count; i++) {
                var slot = plan.Slots[i];
                if (slot.IsTransient == false || string.IsNullOrEmpty(slot.CreateMethod))
                    continue;

                writer.AppendLine(indent + "private " + slot.ImplementationType + " " + slot.CreateMethod + "() {");
                var created = NewExpression(plan, graph, slot.ImplementationType, slot.Registration, "Constructor");
                var construct = Arguments(plan, graph, slot.Registration, "Construct");
                if (construct == null) {
                    writer.AppendLine(body + "return " + created + ";");
                }
                else {
                    writer.AppendLine(body + "var instance = " + created + ";");
                    var method = ConstructName(slot.Registration);
                    if (construct.Count == 0)
                        writer.AppendLine(body + "instance." + method + "();");
                    else
                        writer.AppendLine(body + "instance." + method + "(" + string.Join(", ", construct) + ");");
                    writer.AppendLine(body + "return instance;");
                }

                writer.AppendLine(indent + "}");
                writer.AppendLine();
            }

            for (var i = 0; i < plan.Factories.Count; i++) {
                var factory = plan.Factories[i];
                var slot = plan.Slots[factory.Slot];
                writer.AppendLine(indent + "private " + factory.ReturnType + " " + factory.MethodName + "(" +
                                  factory.DiscriminantType + " " + factory.DiscriminantName +
                                  (plan.NeedsRequest ? ", global::Internal.GeneratedScopeRequest request" : "") + ") {");
                writer.AppendLine(body + "switch (" + factory.DiscriminantName + ") {");
                for (var a = 0; a < slot.Registration.Arms.Count; a++) {
                    var arm = slot.Registration.Arms[a];
                    var discriminant = string.IsNullOrEmpty(arm.Discriminant) ? "default" : arm.Discriminant;
                    var created = NewExpression(plan, graph, arm.ImplementationType, slot.Registration, "Constructor", a);
                    var construct = Arguments(plan, graph, slot.Registration, "Construct", a);
                    if (construct == null) {
                        writer.AppendLine(body + "    case " + discriminant + ": return " + created + ";");
                        continue;
                    }

                    writer.AppendLine(body + "    case " + discriminant + ": {");
                    writer.AppendLine(body + "        var instance = " + created + ";");
                    writer.AppendLine(body + "        instance." + ConstructName(slot.Registration, a) + "(" + string.Join(", ", construct) + ");");
                    writer.AppendLine(body + "        return instance;");
                    writer.AppendLine(body + "    }");
                }

                writer.AppendLine(body + "    default: throw new global::System.ArgumentOutOfRangeException(nameof(" +
                                  factory.DiscriminantName + "), " + factory.DiscriminantName + ", null);");
                writer.AppendLine(body + "}");
                writer.AppendLine(indent + "}");
                writer.AppendLine();
            }
        }

        private static void WriteProvides(
            CodeWriter writer,
            ScopePlan plan,
            ScopeGraph graph,
            string indent,
            string body) {
            for (var i = 0; i < plan.Provides.Count; i++) {
                var provide = plan.Provides[i];
                var slot = plan.Slots[provide.Slot];
                writer.AppendLine(indent + "void global::Internal.IProvides<" + provide.TargetType + ">.Construct(" +
                                  provide.TargetType + " target) {");
                var args = Arguments(plan, graph, slot.Registration, "Construct");
                var method = ConstructName(slot.Registration);
                if (args == null || args.Count == 0)
                    writer.AppendLine(body + "target." + method + "();");
                else
                    writer.AppendLine(body + "target." + method + "(" + string.Join(", ", args) + ");");
                writer.AppendLine(indent + "}");
                writer.AppendLine();
            }
        }

        // Таблица статическая: экземпляр скоупа платит только за объект ContainerDiagnostics.
        private static void WriteDiagnostics(CodeWriter writer, ScopePlan plan, ScopeGraph graph, string indent, string body) {
            if (plan.HasContainerDiagnostics == false)
                return;

            writer.AppendLine("#if UNITY_EDITOR || DEBUG");
            writer.AppendLine(indent + "private static readonly global::Internal.RegistrationInfo[] _registrationInfos = {");
            for (var i = 0; i < plan.DiagnosticRegistrations.Count; i++) {
                var entry = plan.DiagnosticRegistrations[i];
                var comma = i + 1 < plan.DiagnosticRegistrations.Count ? "," : "";
                var implementation = string.IsNullOrEmpty(entry.ImplementationType)
                    ? "null"
                    : "typeof(" + entry.ImplementationType + ")";
                writer.AppendLine(body + "new global::Internal.RegistrationInfo(" +
                                  i.ToString() + ", " +
                                  implementation + ", " +
                                  TypeArray(entry.ServiceTypes) + ", " +
                                  "global::Internal.ServiceLifetime." + LifetimeMember(entry.Lifetime) + ", " +
                                  IntArray(entry.Dependencies) + ", " +
                                  (entry.IsInstantiated ? "true" : "false") + ", " +
                                  (entry.IsExternal ? "true" : "false") + ")" + comma);
            }

            writer.AppendLine(indent + "};");
            writer.AppendLine();
            writer.AppendLine(indent + "private static readonly int[] _buildOrder = " + IntArray(graph.ConstructionOrder) + ";");
            writer.AppendLine("#endif");
        }

        private static string TypeArray(List<string> types) {
            if (types.Count == 0)
                return "global::System.Type.EmptyTypes";

            var items = new List<string>();
            for (var i = 0; i < types.Count; i++)
                items.Add("typeof(" + types[i] + ")");
            return "new global::System.Type[] { " + string.Join(", ", items) + " }";
        }

        private static string IntArray(List<int> values) {
            if (values.Count == 0)
                return "global::System.Array.Empty<int>()";

            var items = new List<string>();
            for (var i = 0; i < values.Count; i++)
                items.Add(values[i].ToString());
            return "new int[] { " + string.Join(", ", items) + " }";
        }

        private static string LifetimeMember(string lifetime) {
            return lifetime == "Transient" || lifetime == "Scoped" ? lifetime : "Singleton";
        }

        private static bool IsContainerType(string type) {
            return type == "global::Internal.IContainer" || type == "Internal.IContainer";
        }

        private static bool TryUnwrapList(string typeFullName, out string elementType) {
            elementType = "";
            const string prefix = "global::System.Collections.Generic.IReadOnlyList<";
            if (typeFullName.StartsWith(prefix, StringComparison.Ordinal) == false)
                return false;
            if (typeFullName.Length <= prefix.Length || typeFullName[typeFullName.Length - 1] != '>')
                return false;
            elementType = typeFullName.Substring(prefix.Length, typeFullName.Length - prefix.Length - 1);
            return true;
        }
    }
}
