using System;
using System.Collections.Generic;
using System.Text;

namespace Internal
{
    public static class SpritesClassGenerator
    {
        public const string GeneratedFolder = "Assets/Common/Internal/Runtime/Catalogues/Sprites/Generated";

        private const string LogTag = "SpritesClassGenerator";

        internal static void Generate(IReadOnlyList<SpriteGroupDefinition> groups)
        {
            CatalogPaths.EnsureFolder(GeneratedFolder);

            GeneratedFile.WriteIfChanged(LogTag, $"{GeneratedFolder}/Sprites.cs", BuildSpritesClass(groups));

            var written = new HashSet<string>(StringComparer.Ordinal)
            {
                "Sprites.cs"
            };

            foreach (var group in groups)
            {
                var fileName = group.ClassName + ".cs";
                written.Add(fileName);
                GeneratedFile.WriteIfChanged(LogTag, $"{GeneratedFolder}/{fileName}", BuildGroupClass(group));
            }

            GeneratedFile.DeleteStale(LogTag, GeneratedFolder, written, ".cs");
        }

        private static string BuildSpritesClass(IReadOnlyList<SpriteGroupDefinition> groups)
        {
            var builder = new StringBuilder();
            builder.AppendLine("// Auto-generated by SpriteGenerator. Do not edit manually.");
            builder.AppendLine("using Unity.Scripting.LifecycleManagement;");
            builder.AppendLine();
            builder.AppendLine("namespace Internal {");
            builder.AppendLine("    [NoAutoStaticsCleanup]");
            builder.AppendLine("    public static class Sprites {");

            foreach (var group in groups)
                builder.AppendLine($"        public static readonly {group.ClassName} {group.Name} = new();");

            builder.AppendLine("    }");
            builder.AppendLine("}");
            return builder.ToString();
        }

        private static string BuildGroupClass(SpriteGroupDefinition group)
        {
            var builder = new StringBuilder();
            var hasSheet = false;

            foreach (var property in group.Properties)
            {
                if (property.Kind != SpriteKind.Animation)
                    hasSheet = true;
            }

            builder.AppendLine("// Auto-generated by SpriteGenerator. Do not edit manually.");
            builder.AppendLine("using Cysharp.Threading.Tasks;");

            if (hasSheet)
                builder.AppendLine("using UnityEngine;");
            builder.AppendLine();
            builder.AppendLine("namespace Internal {");
            builder.AppendLine($"    public sealed class {group.ClassName} : SpriteGroup {{");
            builder.AppendLine($"        private const string Address = \"{group.Address}\";");
            builder.AppendLine();

            foreach (var property in group.Properties)
                builder.AppendLine($"        private {FieldType(property.Kind)} {property.FieldName};");

            builder.AppendLine();

            foreach (var property in group.Properties)
            {
                builder.AppendLine($"        public {PropertyType(property.Kind)} {property.PropertyName} {{");
                builder.AppendLine($"            get {{ EnsureLoaded(); return {property.FieldName}; }}");
                builder.AppendLine("        }");
                builder.AppendLine();
            }

            builder.AppendLine("        protected override async UniTask LoadGroup() {");
            builder.AppendLine("            await LoadAsset(Address);");

            foreach (var property in group.Properties)
            {
                var getter = property.Kind == SpriteKind.Animation ? "GetAnimation" : "GetSheet";
                builder.AppendLine($"            {property.FieldName} = Asset.{getter}(\"{property.PropertyName}\");");
            }

            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        protected override void UnloadGroup() {");

            foreach (var property in group.Properties)
                builder.AppendLine($"            {property.FieldName} = null;");

            builder.AppendLine("            UnloadAsset();");
            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine("}");
            return builder.ToString();
        }

        private static string PropertyType(SpriteKind kind)
        {
            return kind == SpriteKind.Animation ? "ISpriteAnimationData" : "Sprite";
        }

        private static string FieldType(SpriteKind kind)
        {
            return PropertyType(kind);
        }
    }
}