using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEngine;

namespace Tools
{
    public static class PrefabsClassGenerator
    {
        private const string OutputPath = "Assets/Tools/PrefabBuilder/Runtime/Prefabs.cs";

        public static void Generate(List<(string asmdefName, string prefabName, string prefabPath)> prefabs)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// Auto-generated by PrefabBuilder. Do not edit manually.");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();
            sb.AppendLine("namespace Tools");
            sb.AppendLine("{");
            sb.AppendLine("    public static class Prefabs");
            sb.AppendLine("    {");

            foreach (var (_, prefabName, prefabPath) in prefabs.OrderBy(p => p.prefabName))
            {
                var propertyName = SanitizeIdentifier(prefabName);
                var fieldName = $"_{char.ToLower(propertyName[0])}{propertyName.Substring(1)}";
                sb.AppendLine($"        private static GameObject {fieldName};");
                sb.AppendLine(
                    $"        public static GameObject {propertyName} => {fieldName} ??= Resources.Load<GameObject>(\"{prefabPath}\");"
                );
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            var newContent = sb.ToString();
            if (File.Exists(OutputPath))
            {
                var existingContent = File.ReadAllText(OutputPath);
                if (existingContent == newContent) return;
            }

            File.WriteAllText(OutputPath, newContent);
            Debug.Log($"[PrefabsClassGenerator] Generated {OutputPath}");
        }

        private static string SanitizeIdentifier(string name)
        {
            var sb = new StringBuilder(name.Length);
            foreach (var c in name)
            {
                if (char.IsLetterOrDigit(c))
                {
                    sb.Append(c);
                }
            }

            return sb.ToString();
        }
    }
}