using System.Text;
using UnityEngine;

namespace Internal
{
    // Класс биндингов сам является MonoBehaviour: отдельной вьюхи-обёртки нет, поэтому
    // пользовательский класс может просто наследовать сгенерированный и получить свойства
    // напрямую. Дети живут вложенными [Serializable]-классами, ссылки на них Unity сериализует
    // по имени поля — как обычные ручные [SerializeField], со всеми их свойствами при мерже.
    internal static class HierarchyBindingsCodeGenerator
    {
        public const string FileSuffix = "Bindings.g.cs";

        public static string Build(
            HierarchyBindingsNode root,
            string namespaceName,
            string structureHash,
            bool isSceneService,
            bool isEntityComponent)
        {
            var builder = new StringBuilder();
            builder.AppendLine("// Auto-generated by HierarchyBindingsGenerator. Do not edit manually.");
            builder.AppendLine("using System;");
            builder.AppendLine("using UnityEngine;");
            builder.AppendLine();

            var indent = "";
            var hasNamespace = string.IsNullOrEmpty(namespaceName) == false;

            if (hasNamespace)
            {
                builder.AppendLine($"namespace {namespaceName} {{");
                indent = "    ";
            }

            builder.AppendLine($"{indent}// Structure: {structureHash}");
            AppendHierarchy(builder, root, indent, true);
            builder.AppendLine($"{indent}[DisallowMultipleComponent]");
            var bases = "global::Internal.ObjectBindings";

            if (isSceneService)
                bases += ", global::Internal.ISceneService";

            if (isEntityComponent)
                bases += ", global::Internal.IEntityComponent";

            builder.AppendLine($"{indent}public class {root.TypeName} : {bases} {{");

            AppendMembers(builder, root, indent + "    ");
            AppendRegistration(builder, indent + "    ", isSceneService, isEntityComponent);
            AppendNestedClasses(builder, root, indent + "    ");

            builder.AppendLine($"{indent}}}");

            if (hasNamespace)
                builder.AppendLine("}");

            return builder.ToString();
        }

        private static void AppendMembers(StringBuilder builder, HierarchyBindingsNode node, string indent)
        {
            foreach (var field in node.Fields)
            {
                if (string.IsNullOrEmpty(field.Comment) == false)
                    builder.AppendLine($"{indent}// {field.Comment}");

                builder.AppendLine(
                    $"{indent}[SerializeField, HideInInspector] private {field.CodeTypeName} {field.FieldName};");
            }

            if (node.Children.Count > 0)
            {
                if (node.Fields.Count > 0)
                    builder.AppendLine();

                builder.AppendLine($"{indent}// Child objects");

                foreach (var child in node.Children)
                    builder.AppendLine(
                        $"{indent}[SerializeField, HideInInspector] private {child.TypeName} {child.FieldName};");
            }

            builder.AppendLine();

            foreach (var field in node.Fields)
                builder.AppendLine($"{indent}public {field.CodeTypeName} {field.PropertyName} => {field.FieldName};");

            foreach (var child in node.Children)
                builder.AppendLine($"{indent}public {child.TypeName} {child.PropertyName} => {child.FieldName};");
        }

        // Регистрация в DI одинаковая для обоих входов, поэтому её пишет генератор. Методы
        // виртуальные: пользовательский класс наследует сгенерированный и может добавить своё.
        // Расширение вызываем статически, чтобы не тащить в файл using и не зависеть от того,
        // что в целевом неймспейсе может лежать свой тип с таким же именем.
        private static void AppendRegistration(
            StringBuilder builder,
            string indent,
            bool isSceneService,
            bool isEntityComponent)
        {
            if (isSceneService)
            {
                builder.AppendLine();
                builder.AppendLine($"{indent}public virtual void Create(global::Internal.IScopeBuilder builder) {{");
                builder.AppendLine($"{indent}    global::Internal.BuilderExtensions.RegisterComponent(builder, this);");
                builder.AppendLine($"{indent}}}");
            }

            if (isEntityComponent == false)
                return;

            builder.AppendLine();
            builder.AppendLine($"{indent}public virtual void Register(global::Internal.IEntityBuilder builder) {{");
            builder.AppendLine($"{indent}    global::Internal.BuilderExtensions.RegisterComponent(builder, this);");
            builder.AppendLine($"{indent}}}");
        }

        // Карта иерархии в комментарии: поля класса плоские, а зеркало — нет, и без неё
        // непонятно, какой объект стоит за каким свойством. Порядок берём у самих трансформов,
        // чтобы комментарий читался так же, как окно Hierarchy.
        private static void AppendHierarchy(
            StringBuilder builder,
            HierarchyBindingsNode node,
            string indent,
            bool withHeader)
        {
            if (node.Target == null || node.Target.transform.childCount == 0)
                return;

            // Ветку обрубили маркером — показывать нечего, в зеркале детей нет.
            if (node.IgnoreChildren == true)
                return;

            // У вложенных классов имя объекта уже стоит строкой выше — путём от корня.
            if (withHeader)
                builder.AppendLine($"{indent}// {node.Target.name}");

            AppendHierarchyChildren(builder, node, indent, 1);
        }

        private static void AppendHierarchyChildren(
            StringBuilder builder,
            HierarchyBindingsNode node,
            string indent,
            int depth)
        {
            var transform = node.Target.transform;
            var padding = new string(' ', depth * 4 - 2);

            for (var index = 0; index < transform.childCount; index++)
            {
                var child = transform.GetChild(index).gameObject;
                var childNode = FindChild(node, child);

                if (childNode == null)
                {
                    // Ребёнка нет в зеркале — значит у него свои биндинги и внутрь мы не заходим.
                    builder.AppendLine($"{indent}// {padding}- {child.name} (own bindings)");
                    continue;
                }

                if (childNode.IgnoreChildren == true && child.transform.childCount > 0)
                {
                    builder.AppendLine($"{indent}// {padding}- {child.name} (children ignored)");
                    continue;
                }

                builder.AppendLine($"{indent}// {padding}- {child.name}");
                AppendHierarchyChildren(builder, childNode, indent, depth + 1);
            }
        }

        private static HierarchyBindingsNode FindChild(HierarchyBindingsNode node, GameObject child)
        {
            foreach (var candidate in node.Children)
            {
                if (candidate.Target == child)
                    return candidate;
            }

            return null;
        }

        private static void AppendNestedClasses(StringBuilder builder, HierarchyBindingsNode node, string indent)
        {
            foreach (var child in node.Children)
            {
                builder.AppendLine();
                builder.AppendLine($"{indent}// {child.HierarchyPath}");
                AppendHierarchy(builder, child, indent, false);
                builder.AppendLine($"{indent}[Serializable]");
                builder.AppendLine($"{indent}public sealed class {child.TypeName} {{");

                AppendMembers(builder, child, indent + "    ");
                AppendNestedClasses(builder, child, indent + "    ");

                builder.AppendLine($"{indent}}}");
            }
        }
    }
}