using System.Text;
using UnityEngine;

namespace Internal
{
    // Класс биндингов сам является MonoBehaviour: отдельной вьюхи-обёртки нет, поэтому
    // пользовательский класс может просто наследовать сгенерированный и получить свойства
    // напрямую. Дети живут вложенными [Serializable]-классами, ссылки на них Unity сериализует
    // по имени поля — как обычные ручные [SerializeField], со всеми их свойствами при мерже.
    internal static class HierarchyBindingsCodeGenerator
    {
        public const string FileSuffix = "Bindings.g.cs";

        public static string Build(
            HierarchyBindingsNode root,
            string namespaceName,
            string structureHash,
            bool isSceneService,
            bool isEntityComponent)
        {
            var builder = new StringBuilder();
            builder.AppendLine("// Auto-generated by HierarchyBindingsGenerator. Do not edit manually.");
            builder.AppendLine("using System;");
            builder.AppendLine("using UnityEngine;");
            builder.AppendLine();

            var indent = "";
            var hasNamespace = string.IsNullOrEmpty(namespaceName) == false;

            if (hasNamespace)
            {
                builder.AppendLine($"namespace {namespaceName} {{");
                indent = "    ";
            }

            builder.AppendLine($"{indent}// Structure: {structureHash}");
            AppendHierarchy(builder, root, indent, true);
            builder.AppendLine($"{indent}[DisallowMultipleComponent]");
            var bases = "global::Internal.ObjectBindings";

            if (isSceneService)
                bases += ", global::Internal.ISceneService";

            if (isEntityComponent)
                bases += ", global::Internal.IEntityComponent";

            builder.AppendLine($"{indent}public class {root.TypeName} : {bases} {{");

            AppendMembers(builder, root, indent + "    ");
            AppendRegistration(builder, indent + "    ", isSceneService, isEntityComponent);
            AppendNestedClasses(builder, root, indent + "    ");

            builder.AppendLine($"{indent}}}");

            if (hasNamespace)
                builder.AppendLine("}");

            return builder.ToString();
        }

        private static void AppendMembers(StringBuilder builder, HierarchyBindingsNode node, string indent)
        {
            foreach (var field in node.Fields)
            {
                if (string.IsNullOrEmpty(field.Comment) == false)
                    builder.AppendLine($"{indent}// {field.Comment}");

                builder.AppendLine(
                    $"{indent}[SerializeField, HideInInspector] private {field.DeclaredTypeName} {field.FieldName};");
            }

            if (node.Children.Count > 0)
            {
                if (node.Fields.Count > 0)
                    builder.AppendLine();

                builder.AppendLine($"{indent}// Child objects");

                foreach (var child in node.Children)
                    builder.AppendLine(
                        $"{indent}[SerializeField, HideInInspector] private {DeclaredTypeName(child)} {child.FieldName};");
            }

            builder.AppendLine();

            foreach (var field in node.Fields)
                builder.AppendLine(
                    $"{indent}public {field.DeclaredTypeName} {field.PropertyName} => {field.FieldName};");

            foreach (var child in node.Children)
                builder.AppendLine(
                    $"{indent}public {DeclaredTypeName(child)} {child.PropertyName} => {child.FieldName};");
        }

        // Регистрация в DI одинаковая для обоих входов, поэтому её пишет генератор. Методы
        // виртуальные: пользовательский класс наследует сгенерированный и может добавить своё.
        // Расширение вызываем статически, чтобы не тащить в файл using и не зависеть от того,
        // что в целевом неймспейсе может лежать свой тип с таким же именем.
        private static void AppendRegistration(
            StringBuilder builder,
            string indent,
            bool isSceneService,
            bool isEntityComponent)
        {
            if (isSceneService)
            {
                builder.AppendLine();
                builder.AppendLine($"{indent}public virtual void Create(global::Internal.IScopeBuilder builder) {{");
                builder.AppendLine($"{indent}    global::Internal.BuilderExtensions.RegisterComponent(builder, this);");
                builder.AppendLine($"{indent}}}");
            }

            if (isEntityComponent == false)
                return;

            builder.AppendLine();
            builder.AppendLine($"{indent}public virtual void Register(global::Internal.IEntityBuilder builder) {{");
            builder.AppendLine($"{indent}    global::Internal.BuilderExtensions.RegisterComponent(builder, this);");
            builder.AppendLine($"{indent}}}");
        }

        // Карта иерархии в комментарии: поля класса плоские, а зеркало — нет, и без неё
        // непонятно, какой объект стоит за каким свойством. Порядок берём у самих трансформов,
        // чтобы комментарий читался так же, как окно Hierarchy.
        private static void AppendHierarchy(
            StringBuilder builder,
            HierarchyBindingsNode node,
            string indent,
            bool withHeader)
        {
            if (node.Target == null || node.Target.transform.childCount == 0)
                return;

            // Ветку обрубили маркером — показывать нечего, в зеркале детей нет.
            if (node.IgnoreChildren == true)
                return;

            // У вложенных классов имя объекта уже стоит строкой выше — путём от корня.
            if (withHeader)
                builder.AppendLine($"{indent}// {node.Target.name}");

            AppendHierarchyChildren(builder, node, indent, 1);
        }

        private static void AppendHierarchyChildren(
            StringBuilder builder,
            HierarchyBindingsNode node,
            string indent,
            int depth)
        {
            var transform = node.Target.transform;
            var padding = new string(' ', depth * 4 - 2);

            for (var index = 0; index < transform.childCount; index++)
            {
                var child = transform.GetChild(index).gameObject;

                if (TryFindGroup(node, child, out var group, out var boundary, out var elementIndex))
                {
                    // Ряд показываем одной строкой на первом элементе: в классе он всё равно
                    // один массив, а два десятка одинаковых строк карту только засоряют.
                    if (elementIndex > 0)
                        continue;

                    var count = group != null ? group.Elements.Count : boundary.Targets.Count;
                    var last = group != null
                        ? ElementName(group, count - 1)
                        : TargetName(boundary.Targets[count - 1]);
                    var suffix = group != null ? string.Empty : ", own bindings";
                    builder.AppendLine($"{indent}// {padding}- {child.name} .. {last} ({count} items{suffix})");

                    if (group != null && group.IgnoreChildren == false)
                        AppendHierarchyChildren(builder, group, indent, depth + 1);

                    continue;
                }

                var childNode = FindChild(node, child);

                if (childNode == null)
                {
                    // Ребёнка нет в зеркале — значит у него свои биндинги и внутрь мы не заходим.
                    builder.AppendLine($"{indent}// {padding}- {child.name} (own bindings)");
                    continue;
                }

                if (childNode.IgnoreChildren == true && child.transform.childCount > 0)
                {
                    builder.AppendLine($"{indent}// {padding}- {child.name} (children ignored)");
                    continue;
                }

                builder.AppendLine($"{indent}// {padding}- {child.name}");
                AppendHierarchyChildren(builder, childNode, indent, depth + 1);
            }
        }

        // Схлопнутый ряд: либо массив вложенных классов (тогда отдаём шаблонный узел), либо
        // массив ссылок на чужие биндинги (тогда отдаём поле). Позиция нужна, чтобы строка
        // печаталась один раз, на первом элементе.
        private static bool TryFindGroup(
            HierarchyBindingsNode node,
            GameObject child,
            out HierarchyBindingsNode group,
            out HierarchyBindingsField boundary,
            out int elementIndex)
        {
            group = null;
            boundary = null;
            elementIndex = 0;

            foreach (var candidate in node.Children)
            {
                if (candidate.IsArray == false)
                    continue;

                for (var index = 0; index < candidate.Elements.Count; index++)
                {
                    if (candidate.Elements[index].Target != child)
                        continue;

                    group = candidate;
                    elementIndex = index;
                    return true;
                }
            }

            foreach (var field in node.Fields)
            {
                for (var index = 0; index < field.Targets.Count; index++)
                {
                    var component = field.Targets[index] as Component;

                    if (component == null || component.gameObject != child)
                        continue;

                    boundary = field;
                    elementIndex = index;
                    return true;
                }
            }

            return false;
        }

        private static string ElementName(HierarchyBindingsNode group, int index)
        {
            return TargetName(group.Elements[index].Target);
        }

        private static string TargetName(UnityEngine.Object target)
        {
            if (target is Component component)
                return component.gameObject.name;

            return target == null ? "?" : target.name;
        }

        private static HierarchyBindingsNode FindChild(HierarchyBindingsNode node, GameObject child)
        {
            foreach (var candidate in node.Children)
            {
                if (candidate.Target == child)
                    return candidate;
            }

            return null;
        }

        private static string DeclaredTypeName(HierarchyBindingsNode node)
        {
            return node.IsArray ? node.TypeName + "[]" : node.TypeName;
        }

        private static void AppendNestedClasses(StringBuilder builder, HierarchyBindingsNode node, string indent)
        {
            foreach (var child in node.Children)
            {
                builder.AppendLine();

                // Класс группы один на весь ряд, поэтому путь показываем диапазоном: по первому
                // элементу он генерируется, по остальным только заполняются ссылки.
                builder.AppendLine(child.IsArray
                    ? $"{indent}// {child.HierarchyPath} .. {ElementName(child, child.Elements.Count - 1)} ({child.Elements.Count} items)"
                    : $"{indent}// {child.HierarchyPath}");
                AppendHierarchy(builder, child, indent, false);
                builder.AppendLine($"{indent}[Serializable]");
                builder.AppendLine($"{indent}public sealed class {child.TypeName} {{");

                AppendMembers(builder, child, indent + "    ");
                AppendNestedClasses(builder, child, indent + "    ");

                builder.AppendLine($"{indent}}}");
            }
        }
    }
}