using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Generators
{
    [Generator]
    public class CardDispatchGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var compilationProvider = context.CompilationProvider;

            context.RegisterSourceOutput(compilationProvider, static (spc, compilation) =>
            {
                var payloadInterface = compilation.GetTypeByMetadataName("Shared.ICardUsePayload");
                if (payloadInterface == null)
                    return;

                var payloadTypes = CollectPayloadTypes(payloadInterface);
                if (payloadTypes.Count == 0)
                    return;

                spc.AddSource("CardDispatch.g.cs", SourceText.From(GenerateDispatch(payloadTypes), Encoding.UTF8));
                spc.AddSource("CardRegistration.g.cs", SourceText.From(GenerateRegistration(payloadTypes), Encoding.UTF8));
            });
        }

        private static List<string> CollectPayloadTypes(INamedTypeSymbol payloadInterface)
        {
            var results = new List<string>();

            foreach (var attr in payloadInterface.GetAttributes())
            {
                if (attr.AttributeClass?.Name != "MemoryPackUnionAttribute")
                    continue;

                if (attr.ConstructorArguments.Length < 2)
                    continue;

                var typeArg = attr.ConstructorArguments[1];
                if (typeArg.Value is INamedTypeSymbol typeSymbol)
                {
                    var fullName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    results.Add(fullName);
                }
            }

            return results.Distinct().OrderBy(x => x).ToList();
        }

        private static string GenerateDispatch(List<string> payloadTypes)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            sb.AppendLine("using Shared;");
            sb.AppendLine();
            sb.AppendLine("namespace Game.GamePlay;");
            sb.AppendLine();
            sb.AppendLine("public static class CardDispatch {");
            sb.AppendLine("    public static CardUseResult Use(this IServiceProvider provider, IPlayer invoker, ICardUsePayload payload) {");
            sb.AppendLine("        return payload switch {");

            foreach (var type in payloadTypes)
            {
                sb.AppendLine($"            {type} p => provider.GetRequiredService<ICard<{type}>>().Use(invoker, p),");
            }

            sb.AppendLine("            _ => throw new ArgumentOutOfRangeException(nameof(payload), payload.GetType().Name, \"Unknown card payload type\")");
            sb.AppendLine("        };");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static string GenerateRegistration(List<string> payloadTypes)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// Register ICard<TPayload> implementations in the DI container.");
            sb.AppendLine("// Call: services.AddGeneratedCards() in AddCardServices().");
            sb.AppendLine("//");
            sb.AppendLine("// Each card must be registered manually in AddCardServices() as:");
            sb.AppendLine("//   services.Add<Focus>().As<ICard<CardUsePayload.Focus>>();");
            sb.AppendLine("//");
            sb.AppendLine("// This file provides a validation helper to detect missing registrations at startup.");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine();
            sb.AppendLine("namespace Game.GamePlay;");
            sb.AppendLine();
            sb.AppendLine("public static class CardRegistrationValidator {");
            sb.AppendLine("    public static IReadOnlyList<Type> RequiredCardInterfaces => new Type[] {");

            foreach (var type in payloadTypes)
            {
                sb.AppendLine($"        typeof(ICard<{type}>),");
            }

            sb.AppendLine("    };");
            sb.AppendLine("}");

            return sb.ToString();
        }
    }
}
