using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Generators
{
    [Generator]
    public class UserProjectionSourceGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var compilationProvider = context.CompilationProvider;

            context.RegisterSourceOutput(compilationProvider, static (spc, compilation) => {
                var sourceInterface = compilation.GetTypeByMetadataName("Meta.Users.IUserProjectionSource");

                if (sourceInterface == null)
                    return;

                var grainInterfaces = CollectGrainInterfaces(compilation, sourceInterface);

                if (grainInterfaces.Count == 0)
                    return;

                spc.AddSource("GeneratedUserProjections.g.cs",
                    SourceText.From(GenerateMethod(grainInterfaces), Encoding.UTF8));
            });
        }

        private static List<string> CollectGrainInterfaces(Compilation compilation, INamedTypeSymbol sourceInterface)
        {
            var results = new List<string>();

            foreach (var assemblySymbol in GetAllAssemblies(compilation))
            {
                VisitNamespace(assemblySymbol.GlobalNamespace, sourceInterface, results);
            }

            return results;
        }

        private static IEnumerable<IAssemblySymbol> GetAllAssemblies(Compilation compilation)
        {
            yield return compilation.Assembly;

            foreach (var reference in compilation.References)
            {
                var symbol = compilation.GetAssemblyOrModuleSymbol(reference);

                if (symbol is IAssemblySymbol assemblySymbol)
                    yield return assemblySymbol;
            }
        }

        private static void VisitNamespace(INamespaceSymbol ns, INamedTypeSymbol sourceInterface, List<string> results)
        {
            foreach (var type in ns.GetTypeMembers())
            {
                VisitType(type, sourceInterface, results);
            }

            foreach (var childNs in ns.GetNamespaceMembers())
            {
                VisitNamespace(childNs, sourceInterface, results);
            }
        }

        private static void VisitType(INamedTypeSymbol type, INamedTypeSymbol sourceInterface, List<string> results)
        {
            if (type.TypeKind == TypeKind.Interface &&
                !SymbolEqualityComparer.Default.Equals(type, sourceInterface) &&
                ImplementsInterface(type, sourceInterface))
            {
                var fullName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                results.Add(fullName);
            }

            foreach (var nested in type.GetTypeMembers())
            {
                VisitType(nested, sourceInterface, results);
            }
        }

        private static bool ImplementsInterface(INamedTypeSymbol type, INamedTypeSymbol targetInterface)
        {
            foreach (var iface in type.AllInterfaces)
            {
                if (SymbolEqualityComparer.Default.Equals(iface, targetInterface))
                    return true;
            }

            return false;
        }

        private static string GenerateMethod(List<string> grainInterfaces)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using Infrastructure;");
            sb.AppendLine("using Meta.Users;");
            sb.AppendLine();
            sb.AppendLine("namespace Meta.Users;");
            sb.AppendLine();
            sb.AppendLine("public static class GeneratedUserProjections {");

            sb.AppendLine(
                "    public static async Task<IReadOnlyList<IProjectionPayload>> GetAllUserProjections(IOrleans orleans, Guid userId) {");
            sb.AppendLine("        var results = await Task.WhenAll(");

            for (var i = 0; i < grainInterfaces.Count; i++)
            {
                var comma = i < grainInterfaces.Count - 1 ? "," : "";

                sb.AppendLine(
                    "            orleans.GetGrain<" + grainInterfaces[i] + ">(userId).GetProjection()" + comma);
            }

            sb.AppendLine("        );");
            sb.AppendLine("        return results;");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }
    }
}