using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEngine;

namespace Internal {
    public static class AssetsCatalogClassGenerator {
        public const string InternalGeneratedFolder = "Assets/Common/Internal/Runtime/Catalogues/Assets/Generated";

        // Классы каталога делят папку Generated с другими генераторами, поэтому свои файлы
        // опознаём по суффиксу имени.
        private const string OwnedSuffix = "Assets.cs";

        private const string LogTag = "AssetsCatalogClassGenerator";

        internal static void Generate(IReadOnlyList<AssetGroupDefinition> groups) {
            var byFolder = new Dictionary<string, List<AssetGroupDefinition>>(StringComparer.Ordinal);
            foreach (var group in groups) {
                if (group.SkipCodegen)
                    continue;

                if (string.IsNullOrEmpty(group.GeneratedFolder)) {
                    Debug.LogError($"[{LogTag}] Missing generated folder for group '{group.Name}'");
                    continue;
                }

                if (byFolder.TryGetValue(group.GeneratedFolder, out var list) == false) {
                    list = new List<AssetGroupDefinition>();
                    byFolder.Add(group.GeneratedFolder, list);
                }

                list.Add(group);
            }

            var writtenFolders = new HashSet<string>(StringComparer.Ordinal);
            foreach (var pair in byFolder) {
                writtenFolders.Add(pair.Key);
                WriteFolder(pair.Key, pair.Value);
            }

            CleanUnusedGeneratedFolders(writtenFolders);
        }

        public static string GetAssemblyGeneratedFolder(string assemblyName) {
            return CatalogAssemblies.GetGeneratedFolder(LogTag, assemblyName, InternalGeneratedFolder);
        }

        private static void WriteFolder(string folder, List<AssetGroupDefinition> groups) {
            CatalogPaths.EnsureFolder(folder);

            var written = new HashSet<string>(StringComparer.Ordinal);

            foreach (var group in groups) {
                var fileName = group.ClassName + ".cs";
                written.Add(fileName);
                GeneratedFile.WriteIfChanged(LogTag, $"{folder}/{fileName}", BuildGroupClass(group));
            }

            GeneratedFile.DeleteStale(LogTag, folder, written, OwnedSuffix);
        }

        private static string BuildGroupClass(AssetGroupDefinition group) {
            var builder = new StringBuilder();
            builder.AppendLine("// Auto-generated by AssetCatalogGenerator. Do not edit manually.");
            builder.AppendLine($"namespace {group.TargetNamespace} {{");
            builder.AppendLine($"    public static class {group.ClassName} {{");
            builder.AppendLine($"        private const string Group = \"{group.Name}\";");
            builder.AppendLine();

            foreach (var property in group.Properties) {
                var type = "global::" + property.TypeFullName;
                builder.AppendLine($"        public static {type} {property.PropertyName} =>");
                builder.AppendLine(
                    $"            global::Internal.AssetCatalog.Get<{type}>(Group, \"{property.PropertyName}\");");
                builder.AppendLine();
            }

            builder.AppendLine("    }");
            builder.AppendLine("}");
            return builder.ToString();
        }

        private static void CleanUnusedGeneratedFolders(HashSet<string> writtenFolders) {
            if (writtenFolders.Contains(InternalGeneratedFolder) == false)
                GeneratedFile.DeleteFolderScripts(LogTag, InternalGeneratedFolder, OwnedSuffix);

            var assetsRoot = Application.dataPath;
            if (Directory.Exists(assetsRoot) == false)
                return;

            string[] folders;
            try {
                folders = Directory.GetDirectories(assetsRoot, "Generated", SearchOption.AllDirectories);
            }
            catch (Exception exception) {
                Debug.LogError($"[{LogTag}] Failed to scan generated folders: {exception}");
                return;
            }

            var projectRoot = Path.GetDirectoryName(Application.dataPath);
            foreach (var directory in folders) {
                var folder = CatalogPaths.ToAssetPath(projectRoot, directory);
                if (writtenFolders.Contains(folder))
                    continue;

                GeneratedFile.DeleteFolderScripts(LogTag, folder, OwnedSuffix);
            }
        }

    }
}
