<Project>
    <PropertyGroup>
        <BaseIntermediateOutputPath>..\obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
        <OutputPath>..\bin\$(MSBuildProjectName)\$(Configuration)\</OutputPath>
        <MSBuildProjectExtensionsPath>..\obj\</MSBuildProjectExtensionsPath>
    </PropertyGroup>
</Project>