using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using Newtonsoft.Json;
using UnityEditor;
using UnityEngine;

namespace Internal {
    public static class PrefabsCatalogClassGenerator {
        public const string InternalGeneratedFolder = "Assets/Common/Internal/Runtime/Catalogues/Prefabs/Generated";
        public const string CatalogFileName = "Prefabs.Catalog.cs";

        internal static void Generate(IReadOnlyList<PrefabGroupDefinition> groups) {
            var byFolder = new Dictionary<string, List<PrefabGroupDefinition>>(StringComparer.Ordinal);
            foreach (var group in groups) {
                if (group.SkipCodegen)
                    continue;

                if (string.IsNullOrEmpty(group.GeneratedFolder)) {
                    Debug.LogError($"[PrefabsCatalogClassGenerator] Missing generated folder for group '{group.Name}'");
                    continue;
                }

                if (byFolder.TryGetValue(group.GeneratedFolder, out var list) == false) {
                    list = new List<PrefabGroupDefinition>();
                    byFolder.Add(group.GeneratedFolder, list);
                }

                list.Add(group);
            }

            var writtenFolders = new HashSet<string>(StringComparer.Ordinal);
            foreach (var pair in byFolder) {
                writtenFolders.Add(pair.Key);
                WriteFolder(pair.Key, pair.Value);
            }

            CleanUnusedGeneratedFolders(writtenFolders);
        }

        public static string GetAssemblyGeneratedFolder(string assemblyName) {
            if (string.Equals(assemblyName, "Internal", StringComparison.Ordinal))
                return InternalGeneratedFolder;

            if (TryGetAsmdefDirectory(assemblyName, out var directory) == false) {
                Debug.LogError($"[PrefabsCatalogClassGenerator] asmdef '{assemblyName}' not found");
                return InternalGeneratedFolder;
            }

            return directory + "/Generated/PrefabCatalog";
        }

        private static void WriteFolder(string folder, List<PrefabGroupDefinition> groups) {
            EnsureFolder(folder);

            var catalog = groups[0].EmitInternalPartial
                ? BuildInternalPrefabsClass(groups)
                : BuildConsumerPrefabsClass(groups);

            WriteIfChanged($"{folder}/{CatalogFileName}", catalog);

            var written = new HashSet<string>(StringComparer.Ordinal) {
                CatalogFileName
            };

            foreach (var group in groups) {
                var fileName = group.ClassName + ".cs";
                written.Add(fileName);
                WriteIfChanged($"{folder}/{fileName}", BuildGroupClass(group));
            }

            DeleteStale(folder, written);
        }

        private static string BuildInternalPrefabsClass(IReadOnlyList<PrefabGroupDefinition> groups) {
            var builder = new StringBuilder();
            builder.AppendLine("// Auto-generated by PrefabCatalogGenerator. Do not edit manually.");
            builder.AppendLine("namespace Internal {");
            builder.AppendLine("    public static partial class Prefabs {");

            foreach (var group in groups)
                builder.AppendLine($"        public static readonly {group.ClassName} {group.Name} = new();");

            builder.AppendLine("    }");
            builder.AppendLine("}");
            return builder.ToString();
        }

        private static string BuildConsumerPrefabsClass(IReadOnlyList<PrefabGroupDefinition> groups) {
            var builder = new StringBuilder();
            builder.AppendLine("// Auto-generated by PrefabCatalogGenerator. Do not edit manually.");
            builder.AppendLine($"namespace {groups[0].TargetNamespace} {{");
            builder.AppendLine("    public static class Prefabs {");

            foreach (var group in groups)
                builder.AppendLine($"        public static readonly global::Internal.{group.ClassName} {group.Name} = new();");

            builder.AppendLine("    }");
            builder.AppendLine("}");
            return builder.ToString();
        }

        private static string BuildGroupClass(PrefabGroupDefinition group) {
            var builder = new StringBuilder();
            builder.AppendLine("// Auto-generated by PrefabCatalogGenerator. Do not edit manually.");
            builder.AppendLine("using Cysharp.Threading.Tasks;");
            builder.AppendLine();
            builder.AppendLine("namespace Internal {");
            builder.AppendLine($"    public sealed class {group.ClassName} : PrefabGroup {{");
            builder.AppendLine($"        private const string Address = \"{group.Address}\";");
            builder.AppendLine();

            foreach (var property in group.Properties)
                builder.AppendLine($"        private {property.CodeTypeName} {property.FieldName};");

            builder.AppendLine();

            foreach (var property in group.Properties) {
                builder.AppendLine($"        public {property.CodeTypeName} {property.PropertyName} {{");
                builder.AppendLine($"            get {{ EnsureLoaded(); return {property.FieldName}; }}");
                builder.AppendLine("        }");
                builder.AppendLine();
            }

            builder.AppendLine("        protected override async UniTask LoadGroup() {");
            builder.AppendLine("            await LoadAsset(Address);");

            foreach (var property in group.Properties) {
                if (property.IsGameObject)
                    builder.AppendLine($"            {property.FieldName} = Asset.GetGameObject(\"{property.PropertyName}\");");
                else
                    builder.AppendLine($"            {property.FieldName} = Asset.Get<{property.CodeTypeName}>(\"{property.PropertyName}\");");
            }

            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        protected override void UnloadGroup() {");

            foreach (var property in group.Properties)
                builder.AppendLine($"            {property.FieldName} = null;");

            builder.AppendLine("            UnloadAsset();");
            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine("}");
            return builder.ToString();
        }

        private static bool TryGetAsmdefDirectory(string assemblyName, out string directory) {
            directory = null;
            var guids = AssetDatabase.FindAssets("t:asmdef");
            foreach (var guid in guids) {
                var path = AssetDatabase.GUIDToAssetPath(guid);
                try {
                    var fullPath = ToFullPath(path);
                    if (File.Exists(fullPath) == false)
                        continue;

                    var file = JsonConvert.DeserializeObject<AsmdefFile>(File.ReadAllText(fullPath));
                    if (file == null || string.Equals(file.name, assemblyName, StringComparison.Ordinal) == false)
                        continue;

                    directory = Path.GetDirectoryName(path).Replace('\\', '/');
                    return true;
                }
                catch (Exception exception) {
                    Debug.LogError($"[PrefabsCatalogClassGenerator] Failed to read {path}: {exception}");
                }
            }

            return false;
        }

        private static void WriteIfChanged(string assetPath, string content) {
            try {
                var fullPath = ToFullPath(assetPath);
                if (File.Exists(fullPath)) {
                    var existing = File.ReadAllText(fullPath);
                    if (existing == content)
                        return;
                }

                var directory = Path.GetDirectoryName(fullPath);
                if (string.IsNullOrEmpty(directory) == false && Directory.Exists(directory) == false)
                    Directory.CreateDirectory(directory);

                File.WriteAllText(fullPath, content);
                AssetDatabase.ImportAsset(assetPath);
                Debug.Log($"[PrefabsCatalogClassGenerator] Generated {assetPath}");
            }
            catch (Exception exception) {
                Debug.LogError($"[PrefabsCatalogClassGenerator] Failed to write {assetPath}: {exception}");
            }
        }

        private static void DeleteStale(string folder, HashSet<string> writtenNames) {
            if (AssetDatabase.IsValidFolder(folder) == false)
                return;

            string[] files;
            try {
                files = Directory.GetFiles(ToFullPath(folder), "*.cs", SearchOption.TopDirectoryOnly);
            }
            catch (Exception exception) {
                Debug.LogError($"[PrefabsCatalogClassGenerator] Failed to scan {folder}: {exception}");
                return;
            }

            foreach (var file in files) {
                var fileName = Path.GetFileName(file);
                if (writtenNames.Contains(fileName))
                    continue;

                DeleteScript($"{folder}/{fileName}", file);
            }
        }

        private static void CleanUnusedGeneratedFolders(HashSet<string> writtenFolders) {
            if (writtenFolders.Contains(InternalGeneratedFolder) == false)
                DeleteFolderScripts(InternalGeneratedFolder);

            var assetsRoot = Application.dataPath;
            if (Directory.Exists(assetsRoot) == false)
                return;

            string[] catalogs;
            try {
                catalogs = Directory.GetFiles(assetsRoot, CatalogFileName, SearchOption.AllDirectories);
            }
            catch (Exception exception) {
                Debug.LogError($"[PrefabsCatalogClassGenerator] Failed to scan generated catalogs: {exception}");
                return;
            }

            var projectRoot = Path.GetDirectoryName(Application.dataPath);
            foreach (var file in catalogs) {
                var folder = ToAssetPath(projectRoot, Path.GetDirectoryName(file));
                if (writtenFolders.Contains(folder))
                    continue;

                DeleteFolderScripts(folder);
            }
        }

        private static void DeleteFolderScripts(string folder) {
            if (AssetDatabase.IsValidFolder(folder) == false)
                return;

            string[] files;
            try {
                files = Directory.GetFiles(ToFullPath(folder), "*.cs", SearchOption.TopDirectoryOnly);
            }
            catch (Exception exception) {
                Debug.LogError($"[PrefabsCatalogClassGenerator] Failed to scan {folder}: {exception}");
                return;
            }

            foreach (var file in files)
                DeleteScript($"{folder}/{Path.GetFileName(file)}", file);
        }

        private static void DeleteScript(string assetPath, string fullPath) {
            if (AssetDatabase.DeleteAsset(assetPath) == false) {
                try {
                    File.Delete(fullPath);
                }
                catch (Exception exception) {
                    Debug.LogError($"[PrefabsCatalogClassGenerator] Failed to delete {assetPath}: {exception}");
                    return;
                }
            }

            Debug.Log($"[PrefabsCatalogClassGenerator] Deleted stale file: {assetPath}");
        }

        private static void EnsureFolder(string folderPath) {
            if (AssetDatabase.IsValidFolder(folderPath))
                return;

            var parts = folderPath.Split('/');
            var current = parts[0];
            for (var i = 1; i < parts.Length; i++) {
                var next = current + "/" + parts[i];
                if (AssetDatabase.IsValidFolder(next) == false)
                    AssetDatabase.CreateFolder(current, parts[i]);

                current = next;
            }
        }

        private static string ToFullPath(string assetPath) {
            var projectRoot = Path.GetDirectoryName(Application.dataPath);
            return Path.Combine(projectRoot, assetPath);
        }

        private static string ToAssetPath(string projectRoot, string fullPath) {
            var normalized = Path.GetFullPath(fullPath).Replace('\\', '/');
            var root = projectRoot.Replace('\\', '/');
            if (normalized.StartsWith(root, StringComparison.OrdinalIgnoreCase) == false)
                return normalized;

            return normalized.Substring(root.Length).TrimStart('/');
        }

        private sealed class AsmdefFile {
            public string name;
        }
    }
}
