using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEngine;

namespace Internal
{
    public static class PrefabsCatalogClassGenerator
    {
        public const string InternalGeneratedFolder = "Assets/Common/Internal/Runtime/Catalogues/Prefabs/Generated";

        // Классы каталога делят папку Generated с другими генераторами, поэтому свои файлы
        // опознаём по суффиксу имени.
        private const string OwnedSuffix = "Prefabs.cs";

        private const string LogTag = "PrefabsCatalogClassGenerator";

        internal static void Generate(IReadOnlyList<PrefabGroupDefinition> groups)
        {
            var byFolder = new Dictionary<string, List<PrefabGroupDefinition>>(StringComparer.Ordinal);

            foreach (var group in groups)
            {
                if (group.SkipCodegen)
                    continue;

                if (string.IsNullOrEmpty(group.GeneratedFolder))
                {
                    Debug.LogError($"[{LogTag}] Missing generated folder for group '{group.Name}'");
                    continue;
                }

                if (byFolder.TryGetValue(group.GeneratedFolder, out var list) == false)
                {
                    list = new List<PrefabGroupDefinition>();
                    byFolder.Add(group.GeneratedFolder, list);
                }

                list.Add(group);
            }

            var writtenFolders = new HashSet<string>(StringComparer.Ordinal);

            foreach (var pair in byFolder)
            {
                writtenFolders.Add(pair.Key);
                WriteFolder(pair.Key, pair.Value);
            }

            CleanUnusedGeneratedFolders(writtenFolders);
        }

        public static string GetAssemblyGeneratedFolder(string assemblyName)
        {
            return CatalogAssemblies.GetGeneratedFolder(LogTag, assemblyName, InternalGeneratedFolder);
        }

        private static void WriteFolder(string folder, List<PrefabGroupDefinition> groups)
        {
            CatalogPaths.EnsureFolder(folder);

            var written = new HashSet<string>(StringComparer.Ordinal);

            foreach (var group in groups)
            {
                var fileName = group.ClassName + ".cs";
                written.Add(fileName);
                GeneratedFile.WriteIfChanged(LogTag, $"{folder}/{fileName}", BuildGroupClass(group));
            }

            GeneratedFile.DeleteStale(LogTag, folder, written, OwnedSuffix);
        }

        private static string BuildGroupClass(PrefabGroupDefinition group)
        {
            var builder = new StringBuilder();
            builder.AppendLine("// Auto-generated by PrefabCatalogGenerator. Do not edit manually.");
            builder.AppendLine("using Cysharp.Threading.Tasks;");
            builder.AppendLine("using Unity.Scripting.LifecycleManagement;");
            builder.AppendLine();
            builder.AppendLine("namespace Internal {");
            builder.AppendLine("    [NoAutoStaticsCleanup]");
            builder.AppendLine($"    public static class {group.ClassName} {{");

            if (group.IsAddressable)
                builder.AppendLine($"        private const string Address = \"{group.Address}\";");
            else
                builder.AppendLine($"        private const string ResourcePath = \"{group.ResourcePath}\";");

            builder.AppendLine();

            foreach (var property in group.Properties)
                builder.AppendLine($"        private static {property.CodeTypeName} {property.FieldName};");

            builder.AppendLine();
            builder.AppendLine("        public static PrefabGroup Group { get; } = new Loader();");
            builder.AppendLine();
            builder.AppendLine("        public static bool IsLoaded => Group.IsLoaded;");
            builder.AppendLine();

            foreach (var property in group.Properties)
            {
                builder.AppendLine($"        public static {property.CodeTypeName} {property.PropertyName} {{");
                builder.AppendLine($"            get {{ Group.EnsureLoaded(); return {property.FieldName}; }}");
                builder.AppendLine("        }");
                builder.AppendLine();
            }

            builder.AppendLine("        private sealed class Loader : PrefabGroup {");
            builder.AppendLine($"            public override string Name => nameof({group.ClassName});");
            builder.AppendLine();

            if (group.IsAddressable)
            {
                builder.AppendLine("            protected override async UniTask LoadGroup() {");
                builder.AppendLine("                await LoadAsset(Address);");
                AppendFields(builder, group);
                builder.AppendLine("            }");
            }
            else
            {
                // Группа из Resources грузится синхронно: и по Retain, и при первом обращении.
                builder.AppendLine("            public override bool IsAddressable => false;");
                builder.AppendLine();
                builder.AppendLine("            protected override UniTask LoadGroup() {");
                builder.AppendLine("                LoadImmediately();");
                builder.AppendLine("                return UniTask.CompletedTask;");
                builder.AppendLine("            }");
                builder.AppendLine();
                builder.AppendLine("            protected override void LoadImmediately() {");
                builder.AppendLine("                LoadResource(ResourcePath);");
                AppendFields(builder, group);
                builder.AppendLine("            }");
            }
            builder.AppendLine();
            builder.AppendLine("            protected override void UnloadGroup() {");

            foreach (var property in group.Properties)
                builder.AppendLine($"                {property.FieldName} = null;");

            builder.AppendLine("                UnloadAsset();");
            builder.AppendLine("            }");
            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine("}");
            return builder.ToString();
        }

        private static void AppendFields(StringBuilder builder, PrefabGroupDefinition group)
        {
            foreach (var property in group.Properties)
            {
                if (property.IsGameObject)
                    builder.AppendLine(
                        $"                {property.FieldName} = Asset.GetGameObject(\"{property.PropertyName}\");");
                else
                    builder.AppendLine(
                        $"                {property.FieldName} = Asset.Get<{property.CodeTypeName}>(\"{property.PropertyName}\");");
            }
        }

        // Папку с прошлого запуска узнаём по имени: группа могла переехать в другую сборку,
        // и её старые классы надо снести.
        private static void CleanUnusedGeneratedFolders(HashSet<string> writtenFolders)
        {
            if (writtenFolders.Contains(InternalGeneratedFolder) == false)
                GeneratedFile.DeleteFolderScripts(LogTag, InternalGeneratedFolder, OwnedSuffix);

            var assetsRoot = Application.dataPath;

            if (Directory.Exists(assetsRoot) == false)
                return;

            string[] folders;

            try
            {
                folders = Directory.GetDirectories(assetsRoot, "Generated", SearchOption.AllDirectories);
            }
            catch (Exception exception)
            {
                Debug.LogError($"[{LogTag}] Failed to scan generated folders: {exception}");
                return;
            }

            var projectRoot = Path.GetDirectoryName(Application.dataPath);

            foreach (var directory in folders)
            {
                var folder = CatalogPaths.ToAssetPath(projectRoot, directory);

                if (writtenFolders.Contains(folder))
                    continue;

                GeneratedFile.DeleteFolderScripts(LogTag, folder, OwnedSuffix);
            }
        }
    }
}