// Auto-generated by PrefabBuilder. Do not edit manually.
using UnityEngine;

namespace Tools
{
    public static class Prefabs
    {
        public static readonly StaticPrefab ActionLogPanel = new("Game/ActionLogPanel");
        public static readonly StaticPrefab ActionLogTile = new("Game/ActionLogTile");
        public static readonly StaticPrefab CardLocal = new("Game/Card_Local");
        public static readonly StaticPrefab CardRemote = new("Game/Card_Remote");
        public static readonly StaticPrefab DeckCard = new("Game/DeckCard");
        public static readonly StaticPrefab ManaPoint = new("Game/ManaPoint");
        public static readonly StaticPrefab PlayerTurnPoint = new("Game/PlayerTurnPoint");
        public static readonly StaticPrefab StashCard = new("Game/StashCard");
        public static readonly StaticPrefab GlobalAudioListener = new("Global/Global_Audio_Listener");
        public static readonly StaticPrefab GlobalAudioPlayer = new("Global/Global_Audio_Player");
        public static readonly StaticPrefab GlobalCamera = new("Global/Global_Camera");
        public static readonly StaticPrefab GlobalEvents = new("Global/Global_Events");
        public static readonly StaticPrefab GlobalUpdater = new("Global/GlobalUpdater");
        public static readonly StaticPrefab InternalScope = new("Global/InternalScope");
        public static readonly StaticPrefab LoadingScreen = new("Global/LoadingScreen");
        public static readonly StaticPrefab MenuPlayer = new("Menu/MenuPlayer");
    }
}
