// Auto-generated by PrefabBuilder. Do not edit manually.
using UnityEngine;

namespace Tools
{
    public static class Prefabs
    {
        public static readonly StaticPrefab CardLocal = new("Card_Local");
        public static readonly StaticPrefab CardRemote = new("Card_Remote");
        public static readonly StaticPrefab DeckCard = new("DeckCard");
        public static readonly StaticPrefab GlobalAudioListener = new("Global_Audio_Listener");
        public static readonly StaticPrefab GlobalAudioPlayer = new("Global_Audio_Player");
        public static readonly StaticPrefab GlobalCamera = new("Global_Camera");
        public static readonly StaticPrefab GlobalEvents = new("Global_Events");
        public static readonly StaticPrefab GlobalUpdater = new("GlobalUpdater");
        public static readonly StaticPrefab InternalScope = new("InternalScope");
        public static readonly StaticPrefab LoadingScreen = new("LoadingScreen");
        public static readonly StaticPrefab ManaPoint = new("ManaPoint");
        public static readonly StaticPrefab MenuPlayer = new("MenuPlayer");
        public static readonly StaticPrefab Mines = new("Mines");
        public static readonly StaticPrefab PlayerTurnPoint = new("PlayerTurnPoint");
        public static readonly StaticPrefab Settings = new("Settings");
        public static readonly StaticPrefab SettingsSlider = new("SettingsSlider");
        public static readonly StaticPrefab StashCard = new("StashCard");
    }
}
