using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace Internal {
    public static class SpritesClassGenerator {
        public const string GeneratedFolder = "Assets/Internal/Runtime/Catalogues/Sprites/Generated";

        internal static void Generate(IReadOnlyList<SpriteGroupDefinition> groups) {
            EnsureFolder(GeneratedFolder);

            WriteIfChanged($"{GeneratedFolder}/Sprites.cs", BuildSpritesClass(groups));

            var written = new HashSet<string>(StringComparer.Ordinal) {
                "Sprites.cs"
            };

            foreach (var group in groups) {
                var fileName = group.ClassName + ".cs";
                written.Add(fileName);
                WriteIfChanged($"{GeneratedFolder}/{fileName}", BuildGroupClass(group));
            }

            DeleteStale(written);
        }

        private static string BuildSpritesClass(IReadOnlyList<SpriteGroupDefinition> groups) {
            var builder = new StringBuilder();
            builder.AppendLine("// Auto-generated by SpriteGenerator. Do not edit manually.");
            builder.AppendLine("namespace Internal {");
            builder.AppendLine("    public static class Sprites {");

            foreach (var group in groups)
                builder.AppendLine($"        public static readonly {group.ClassName} {group.Name} = new();");

            builder.AppendLine("    }");
            builder.AppendLine("}");
            return builder.ToString();
        }

        private static string BuildGroupClass(SpriteGroupDefinition group) {
            var builder = new StringBuilder();
            var hasSheet = false;
            foreach (var property in group.Properties) {
                if (property.Kind != SpriteKind.Animation)
                    hasSheet = true;
            }

            builder.AppendLine("// Auto-generated by SpriteGenerator. Do not edit manually.");
            builder.AppendLine("using Cysharp.Threading.Tasks;");
            if (hasSheet)
                builder.AppendLine("using UnityEngine;");
            builder.AppendLine("using UnityEngine.AddressableAssets;");
            builder.AppendLine("using UnityEngine.ResourceManagement.AsyncOperations;");
            builder.AppendLine();
            builder.AppendLine("namespace Internal {");
            builder.AppendLine($"    public sealed class {group.ClassName} : SpriteGroup {{");
            builder.AppendLine($"        private const string Address = \"{group.Address}\";");
            builder.AppendLine();

            foreach (var property in group.Properties)
                builder.AppendLine($"        private {FieldType(property.Kind)} {property.FieldName};");

            builder.AppendLine("        private AsyncOperationHandle<SpriteGroupAsset> _handle;");
            builder.AppendLine();

            foreach (var property in group.Properties) {
                builder.AppendLine($"        public {PropertyType(property.Kind)} {property.PropertyName} {{");
                builder.AppendLine($"            get {{ EnsureLoaded(); return {property.FieldName}; }}");
                builder.AppendLine("        }");
                builder.AppendLine();
            }

            builder.AppendLine("        protected override async UniTask LoadGroup() {");
            builder.AppendLine("            _handle = Addressables.LoadAssetAsync<SpriteGroupAsset>(Address);");
            builder.AppendLine("            var asset = await _handle.ToUniTask();");

            foreach (var property in group.Properties) {
                var getter = property.Kind == SpriteKind.Animation ? "GetAnimation" : "GetSheet";
                builder.AppendLine($"            {property.FieldName} = asset.{getter}(\"{property.PropertyName}\");");
            }

            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        protected override void UnloadGroup() {");

            foreach (var property in group.Properties)
                builder.AppendLine($"            {property.FieldName} = null;");

            builder.AppendLine("            if (_handle.IsValid())");
            builder.AppendLine("                Addressables.Release(_handle);");
            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine("}");
            return builder.ToString();
        }

        private static void WriteIfChanged(string assetPath, string content) {
            try {
                var fullPath = ToFullPath(assetPath);
                if (File.Exists(fullPath)) {
                    var existing = File.ReadAllText(fullPath);
                    if (existing == content)
                        return;
                }

                var directory = Path.GetDirectoryName(fullPath);
                if (string.IsNullOrEmpty(directory) == false && Directory.Exists(directory) == false)
                    Directory.CreateDirectory(directory);

                File.WriteAllText(fullPath, content);
                AssetDatabase.ImportAsset(assetPath);
                Debug.Log($"[SpritesClassGenerator] Generated {assetPath}");
            }
            catch (Exception exception) {
                Debug.LogError($"[SpritesClassGenerator] Failed to write {assetPath}: {exception}");
            }
        }

        private static void DeleteStale(HashSet<string> writtenNames) {
            if (AssetDatabase.IsValidFolder(GeneratedFolder) == false)
                return;

            string[] files;
            try {
                files = Directory.GetFiles(ToFullPath(GeneratedFolder), "*.cs", SearchOption.TopDirectoryOnly);
            }
            catch (Exception exception) {
                Debug.LogError($"[SpritesClassGenerator] Failed to scan {GeneratedFolder}: {exception}");
                return;
            }

            foreach (var file in files) {
                var fileName = Path.GetFileName(file);
                if (writtenNames.Contains(fileName))
                    continue;

                var assetPath = $"{GeneratedFolder}/{fileName}";
                if (AssetDatabase.DeleteAsset(assetPath) == false) {
                    try {
                        File.Delete(file);
                    }
                    catch (Exception exception) {
                        Debug.LogError($"[SpritesClassGenerator] Failed to delete {assetPath}: {exception}");
                    }
                }

                Debug.Log($"[SpritesClassGenerator] Deleted stale file: {assetPath}");
            }
        }

        private static string PropertyType(SpriteKind kind) {
            return kind == SpriteKind.Animation ? "ISpriteAnimationData" : "Sprite";
        }

        private static string FieldType(SpriteKind kind) {
            return PropertyType(kind);
        }

        private static void EnsureFolder(string folderPath) {
            if (AssetDatabase.IsValidFolder(folderPath))
                return;

            var parts = folderPath.Split('/');
            var current = parts[0];
            for (var i = 1; i < parts.Length; i++) {
                var next = current + "/" + parts[i];
                if (AssetDatabase.IsValidFolder(next) == false)
                    AssetDatabase.CreateFolder(current, parts[i]);

                current = next;
            }
        }

        private static string ToFullPath(string assetPath) {
            var projectRoot = Path.GetDirectoryName(Application.dataPath);
            return Path.Combine(projectRoot, assetPath);
        }
    }
}
