using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;

namespace ContainerGenerator {
    internal static class GraphEmitter {
        public const string AttributeMetadataName = "Internal.ContainerInstallerAttribute";
        public const string BlobVersion = "v1";
        public const string VoidSentinel = "global::System.Void";

        public static string Emit(GraphDocument document) {
            return Emit(document, null);
        }

        public static string Emit(GraphDocument document, Compilation? compilation) {
            var writer = new CodeWriter();
            writer.AppendLine("// <auto-generated/>");
            writer.AppendLine("#pragma warning disable");
            writer.AppendLine();

            var types = compilation != null ? new TypeIndex(compilation) : null;
            for (var i = 0; i < document.Methods.Count; i++) {
                var method = document.Methods[i];
                if (ScopePlan.IsHarvest(method.Id))
                    continue;
                if (string.IsNullOrEmpty(method.Variant) == false)
                    continue;
                if (string.IsNullOrEmpty(method.AssemblyName) == false &&
                    string.IsNullOrEmpty(document.AssemblyName) == false &&
                    string.Equals(method.AssemblyName, document.AssemblyName, StringComparison.Ordinal) == false)
                    continue;
                WriteAssemblyAttribute(writer, method, types);
            }

            return writer.ToString();
        }

        private static void WriteAssemblyAttribute(CodeWriter writer, GraphMethod method, TypeIndex? types) {
            var implementations = new List<string>();
            var services = new List<string>();
            for (var i = 0; i < method.Registrations.Count; i++) {
                var registration = method.Registrations[i];
                implementations.Add(TypeOf(types, TypeOfTarget(registration.ImplementationType, registration.TypeMap)));
                for (var s = 0; s < registration.ServiceTypes.Count; s++) {
                    var map = s < registration.ServiceMaps.Count ? registration.ServiceMaps[s] : "";
                    services.Add(TypeOf(types, TypeOfTarget(registration.ServiceTypes[s], map)));
                }
            }

            writer.AppendLine("[assembly: global::Internal.ContainerInstaller(");
            writer.AppendLine("    " + Literal(method.Id) + ",");
            writer.AppendLine("    " + (method.IsRoot ? "true" : "false") + ",");
            writer.AppendLine("    " + Literal(method.File) + ",");
            writer.AppendLine("    " + method.Line.ToString(CultureInfo.InvariantCulture) + ",");
            WriteTypeArray(writer, implementations);
            writer.AppendLine(",");
            WriteTypeArray(writer, services);
            writer.AppendLine(",");
            writer.AppendLine("    new string[] {");
            for (var i = 0; i < method.Calls.Count; i++) {
                var comma = i + 1 < method.Calls.Count ? "," : "";
                writer.AppendLine("        " + Literal(method.Calls[i]) + comma);
            }

            writer.AppendLine("    },");
            writer.AppendLine("    " + Literal(WriteBlob(method)) + ")]");
        }

        private static void WriteTypeArray(CodeWriter writer, List<string> types) {
            writer.AppendLine("    new global::System.Type[] {");
            for (var i = 0; i < types.Count; i++) {
                var comma = i + 1 < types.Count ? "," : "";
                var type = types[i] == VoidSentinel ? "void" : types[i];
                writer.AppendLine("        typeof(" + type + ")" + comma);
            }

            writer.AppendLine("    }");
        }

        private static string TypeOfTarget(string template, string map) {
            if (string.IsNullOrEmpty(map) == false && map[0] == 'T')
                return "";
            if (string.IsNullOrEmpty(template) || template.IndexOf('{') < 0)
                return template;
            return TypeSubstitution.ToUnbound(template);
        }

        private static string TypeOf(TypeIndex? types, string fullyQualified) {
            if (string.IsNullOrEmpty(fullyQualified))
                return VoidSentinel;
            if (types == null)
                return fullyQualified;

            var symbol = types.Find(fullyQualified);
            if (symbol != null) {
                if (symbol.IsGenericType &&
                    (symbol.IsUnboundGenericType || LooksUnbound(fullyQualified) || ContainsTypeParameter(symbol))) {
                    var unbound = symbol.IsUnboundGenericType ? symbol : symbol.ConstructUnboundGenericType();
                    return TypeNames.ForCode(unbound);
                }

                if (ContainsTypeParameter(symbol))
                    return VoidSentinel;
                return TypeNames.ForCode(symbol);
            }

            return ContainsPlaceholder(fullyQualified) ? VoidSentinel : fullyQualified;
        }

        private static bool LooksUnbound(string type) {
            return string.IsNullOrEmpty(type) == false &&
                   (type.IndexOf("<>", StringComparison.Ordinal) >= 0 ||
                    type.IndexOf("<,", StringComparison.Ordinal) >= 0);
        }

        private static bool ContainsPlaceholder(string value) {
            return string.IsNullOrEmpty(value) == false && value.IndexOf('{') >= 0;
        }

        private static bool ContainsTypeParameter(ITypeSymbol type) {
            if (type == null)
                return false;
            if (type is ITypeParameterSymbol)
                return true;
            if (type is INamedTypeSymbol named) {
                if (named.IsUnboundGenericType)
                    return false;
                for (var i = 0; i < named.TypeArguments.Length; i++) {
                    if (ContainsTypeParameter(named.TypeArguments[i]))
                        return true;
                }
            }

            if (type is IArrayTypeSymbol array)
                return ContainsTypeParameter(array.ElementType);
            return false;
        }

        public static string WriteBlob(GraphMethod method) {
            var builder = new StringBuilder();
            builder.Append(BlobVersion);
            builder.Append('\n');
            builder.Append("parent:");
            builder.Append(string.IsNullOrEmpty(method.ParentId) ? method.ParentHint : method.ParentId);
            builder.Append('\n');
            builder.Append("calls:");
            for (var i = 0; i < method.CallOrdinals.Count; i++) {
                if (i > 0)
                    builder.Append(',');
                builder.Append(method.CallOrdinals[i].ToString(CultureInfo.InvariantCulture));
            }

            builder.Append('\n');
            builder.Append("return:");
            builder.Append(method.ReturnedOrdinal.ToString(CultureInfo.InvariantCulture));
            builder.Append('\n');
            method.PadCallLists();
            builder.Append("calltypes:");
            for (var i = 0; i < method.Calls.Count; i++) {
                if (i > 0)
                    builder.Append('|');
                builder.Append(Escape(method.CallTypeArguments[i]));
            }

            builder.Append('\n');
            builder.Append("callas:");
            for (var i = 0; i < method.Calls.Count; i++) {
                if (i > 0)
                    builder.Append('|');
                builder.Append(Escape(method.CallAsServices[i]));
            }

            builder.Append('\n');
            builder.Append("callholes:");
            for (var i = 0; i < method.Calls.Count; i++) {
                if (i > 0)
                    builder.Append('|');
                builder.Append(Escape(method.CallHoles[i]));
            }

            builder.Append('\n');
            for (var i = 0; i < method.Registrations.Count; i++) {
                var registration = method.Registrations[i];
                builder.Append(Escape(registration.Kind));
                builder.Append('|');
                builder.Append(Escape(registration.Lifetime));
                builder.Append('|');
                builder.Append(Escape(registration.Origin));
                builder.Append('|');
                builder.Append(registration.Ordinal.ToString(CultureInfo.InvariantCulture));
                builder.Append('|');
                builder.Append(registration.ServiceTypes.Count.ToString(CultureInfo.InvariantCulture));
                builder.Append('|');
                builder.Append(registration.Arms.Count.ToString(CultureInfo.InvariantCulture));
                builder.Append('|');
                builder.Append(Escape(registration.Hole));
                builder.Append('|');
                builder.Append(Escape(registration.Source));
                builder.Append('|');
                builder.Append(Escape(registration.File));
                builder.Append('|');
                builder.Append(registration.Line.ToString(CultureInfo.InvariantCulture));
                builder.Append('|');
                builder.Append(Escape(registration.ImplementationType));
                builder.Append('|');
                builder.Append(Escape(registration.TypeMap));
                builder.Append('|');
                builder.Append(Escape(string.Join(";", registration.ServiceMaps.ToArray())));
                builder.Append('\n');
                for (var a = 0; a < registration.Arms.Count; a++) {
                    var arm = registration.Arms[a];
                    builder.Append(Escape(arm.Discriminant));
                    builder.Append('|');
                    builder.Append(Escape(arm.ImplementationType));
                    builder.Append('|');
                    builder.Append(Escape(arm.ParameterExpression));
                    builder.Append('\n');
                }
            }

            return builder.ToString();
        }

        public static string Escape(string value) {
            if (string.IsNullOrEmpty(value))
                return "";
            return value.Replace("\\", "\\\\").Replace("|", "\\|").Replace("\r", "").Replace("\n", "\\n");
        }

        public static string Unescape(string value) {
            if (string.IsNullOrEmpty(value))
                return "";

            var builder = new StringBuilder();
            for (var i = 0; i < value.Length; i++) {
                if (value[i] == '\\' && i + 1 < value.Length) {
                    var next = value[i + 1];
                    if (next == '\\' || next == '|') {
                        builder.Append(next);
                        i++;
                        continue;
                    }

                    if (next == 'n') {
                        builder.Append('\n');
                        i++;
                        continue;
                    }
                }

                builder.Append(value[i]);
            }

            return builder.ToString();
        }

        public static string[] SplitFields(string line) {
            var fields = new List<string>();
            var current = new StringBuilder();
            for (var i = 0; i < line.Length; i++) {
                if (line[i] == '\\' && i + 1 < line.Length) {
                    current.Append('\\');
                    current.Append(line[i + 1]);
                    i++;
                    continue;
                }

                if (line[i] == '|') {
                    fields.Add(current.ToString());
                    current.Clear();
                    continue;
                }

                current.Append(line[i]);
            }

            fields.Add(current.ToString());
            return fields.ToArray();
        }

        private static string Literal(string value) {
            if (value == null)
                value = "";
            return "@\"" + value.Replace("\"", "\"\"") + "\"";
        }
    }
}
