using System.Collections.Generic;
using System.Globalization;

namespace ContainerGenerator {
    internal static class GraphEmitter {
        public static string Emit(GraphDocument document) {
            var writer = new CodeWriter();
            writer.AppendLine("// <auto-generated/>");
            writer.AppendLine("#pragma warning disable");
            writer.AppendLine("using System;");
            writer.AppendLine();
            writer.AppendLine("namespace Internal {");
            writer.AppendLine("    public static partial class ContainerGraph {");
            writer.AppendLine("        public const string AssemblyName = " + Literal(document.AssemblyName) + ";");
            writer.AppendLine();
            WriteRoots(writer, document);
            writer.AppendLine();
            writer.AppendLine("        public static readonly ContainerGraphMethod[] Methods = new ContainerGraphMethod[] {");
            for (var i = 0; i < document.Methods.Count; i++) {
                WriteMethod(writer, document.Methods[i]);
                writer.AppendLine(i + 1 < document.Methods.Count ? "            ," : "            ");
            }

            writer.AppendLine("        };");
            WriteFactories(writer, document);
            writer.AppendLine("    }");
            writer.AppendLine("}");
            return writer.ToString();
        }

        private static void WriteRoots(CodeWriter writer, GraphDocument document) {
            var roots = new List<string>();
            foreach (var method in document.Methods) {
                if (method.IsRoot)
                    roots.Add(method.Id);
            }

            writer.AppendLine("        public static readonly string[] CodeRoots = new string[] {");
            for (var i = 0; i < roots.Count; i++) {
                var comma = i + 1 < roots.Count ? "," : "";
                writer.AppendLine("            " + Literal(roots[i]) + comma);
            }

            writer.AppendLine("        };");
        }

        private static void WriteMethod(CodeWriter writer, GraphMethod method) {
            writer.AppendLine("            new ContainerGraphMethod(");
            writer.AppendLine("                " + Literal(method.Id) + ",");
            writer.AppendLine("                " + (method.IsRoot ? "true" : "false") + ",");
            writer.AppendLine("                " + Literal(method.File) + ",");
            writer.AppendLine("                " + method.Line.ToString(CultureInfo.InvariantCulture) + ",");
            writer.AppendLine("                new ContainerGraphRegistration[] {");
            for (var i = 0; i < method.Registrations.Count; i++) {
                WriteRegistration(writer, method.Registrations[i]);
                writer.AppendLine(i + 1 < method.Registrations.Count ? "                    ," : "                    ");
            }

            writer.AppendLine("                },");
            writer.AppendLine("                new string[] {");
            for (var i = 0; i < method.Calls.Count; i++) {
                var comma = i + 1 < method.Calls.Count ? "," : "";
                writer.AppendLine("                    " + Literal(method.Calls[i]) + comma);
            }

            writer.AppendLine("                })");
        }

        private static void WriteRegistration(CodeWriter writer, GraphRegistration registration) {
            writer.AppendLine("                    new ContainerGraphRegistration(");
            writer.AppendLine("                        " + Literal(registration.Kind) + ",");
            writer.AppendLine("                        " + Literal(registration.ImplementationType) + ",");
            writer.AppendLine("                        new string[] {");
            for (var i = 0; i < registration.ServiceTypes.Count; i++) {
                var comma = i + 1 < registration.ServiceTypes.Count ? "," : "";
                writer.AppendLine("                            " + Literal(registration.ServiceTypes[i]) + comma);
            }

            writer.AppendLine("                        },");
            writer.AppendLine("                        " + Literal(registration.Lifetime) + ",");
            writer.AppendLine("                        global::Internal.ContainerGraphOrigin." + registration.Origin + ",");
            writer.AppendLine("                        " + Literal(registration.Source) + ",");
            writer.AppendLine("                        " + Literal(registration.Hole) + ",");
            writer.AppendLine("                        " + Literal(registration.File) + ",");
            writer.AppendLine("                        " + registration.Line.ToString(CultureInfo.InvariantCulture) + ",");
            writer.AppendLine("                        new ContainerGraphSwitchArm[] {");
            for (var i = 0; i < registration.Arms.Count; i++) {
                var arm = registration.Arms[i];
                var comma = i + 1 < registration.Arms.Count ? "," : "";
                writer.AppendLine(
                    "                            new ContainerGraphSwitchArm(" +
                    Literal(arm.Discriminant) + ", " +
                    Literal(arm.ImplementationType) + ", " +
                    Literal(arm.ParameterExpression) + ")" + comma);
            }

            writer.AppendLine("                        })");
        }

        private static void WriteFactories(CodeWriter writer, GraphDocument document) {
            GraphRegistration? cardAction = null;
            foreach (var method in document.Methods) {
                foreach (var registration in method.Registrations) {
                    if (registration.Origin != "SwitchFactory" || registration.Arms.Count == 0)
                        continue;
                    if (LooksLikeCardAction(registration))
                        cardAction = registration;
                }
            }

            if (cardAction == null)
                return;

            writer.AppendLine();
            writer.AppendLine("        public static class Factories {");
            writer.AppendLine("            public static (System.Type Implementation, string ConfigMember) CreateCardAction(string discriminant) {");
            writer.AppendLine("                switch (discriminant) {");
            foreach (var arm in cardAction.Arms) {
                var config = arm.ParameterExpression;
                var member = ConfigMember(config);
                writer.AppendLine("                    case " + Literal(arm.Discriminant) + ": return (typeof(" + arm.ImplementationType + "), " + Literal(member) + ");");
            }

            writer.AppendLine("                    default: throw new System.ArgumentOutOfRangeException(nameof(discriminant), discriminant, null);");
            writer.AppendLine("                }");
            writer.AppendLine("            }");
            writer.AppendLine("        }");
        }

        private static bool LooksLikeCardAction(GraphRegistration registration) {
            if (registration.ImplementationType.IndexOf("Card", System.StringComparison.Ordinal) >= 0)
                return true;
            foreach (var arm in registration.Arms) {
                if (arm.ImplementationType.IndexOf("Card", System.StringComparison.Ordinal) >= 0 &&
                    arm.ImplementationType.IndexOf("Action", System.StringComparison.Ordinal) >= 0)
                    return true;
            }

            return registration.Arms.Count >= 20;
        }

        private static string ConfigMember(string expression) {
            if (string.IsNullOrEmpty(expression))
                return "";

            var lastDot = expression.LastIndexOf('.');
            if (lastDot < 0 || lastDot + 1 >= expression.Length)
                return expression;

            return expression.Substring(lastDot + 1);
        }

        private static string Literal(string value) {
            if (value == null)
                value = "";
            return "@\"" + value.Replace("\"", "\"\"") + "\"";
        }
    }
}
