using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;

namespace ContainerGenerator {
    internal static class GraphEmitter {
        public const string AttributeMetadataName = "Internal.ContainerInstallerAttribute";
        public const string BlobVersion = "v1";
        public const string VoidSentinel = "global::System.Void";

        public static string Emit(GraphDocument document) {
            return Emit(document, null);
        }

        public static string? EmitAttributeClass(Compilation? compilation) {
            if (compilation != null && compilation.GetTypeByMetadataName(AttributeMetadataName) != null)
                return null;

            var writer = new CodeWriter();
            writer.AppendLine("// <auto-generated/>");
            writer.AppendLine("#pragma warning disable");
            writer.AppendLine();
            WriteAttributeClass(writer);
            return writer.ToString();
        }

        public static string Emit(GraphDocument document, Compilation? compilation) {
            var writer = new CodeWriter();
            writer.AppendLine("// <auto-generated/>");
            writer.AppendLine("#pragma warning disable");
            writer.AppendLine();

            var types = compilation != null ? new TypeIndex(compilation) : null;
            for (var i = 0; i < document.Methods.Count; i++) {
                var method = document.Methods[i];
                if (ScopePlan.IsHarvest(method.Id))
                    continue;
                if (string.IsNullOrEmpty(method.Variant) == false)
                    continue;
                WriteAssemblyAttribute(writer, method, types);
            }

            return writer.ToString();
        }

        private static void WriteAttributeClass(CodeWriter writer) {
            writer.AppendLine("namespace Internal {");
            writer.AppendLine("    [global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = true, Inherited = false)]");
            writer.AppendLine("    public sealed class ContainerInstallerAttribute : global::System.Attribute {");
            writer.AppendLine("        public ContainerInstallerAttribute(");
            writer.AppendLine("            string methodId,");
            writer.AppendLine("            bool isRoot,");
            writer.AppendLine("            string file,");
            writer.AppendLine("            int line,");
            writer.AppendLine("            global::System.Type[] implementations,");
            writer.AppendLine("            global::System.Type[] services,");
            writer.AppendLine("            string[] calls,");
            writer.AppendLine("            string blob) {");
            writer.AppendLine("            MethodId = methodId ?? \"\";");
            writer.AppendLine("            IsRoot = isRoot;");
            writer.AppendLine("            File = file ?? \"\";");
            writer.AppendLine("            Line = line;");
            writer.AppendLine("            Implementations = implementations ?? global::System.Array.Empty<global::System.Type>();");
            writer.AppendLine("            Services = services ?? global::System.Array.Empty<global::System.Type>();");
            writer.AppendLine("            Calls = calls ?? global::System.Array.Empty<string>();");
            writer.AppendLine("            Blob = blob ?? \"\";");
            writer.AppendLine("        }");
            writer.AppendLine();
            writer.AppendLine("        public string MethodId { get; }");
            writer.AppendLine("        public bool IsRoot { get; }");
            writer.AppendLine("        public string File { get; }");
            writer.AppendLine("        public int Line { get; }");
            writer.AppendLine("        public global::System.Type[] Implementations { get; }");
            writer.AppendLine("        public global::System.Type[] Services { get; }");
            writer.AppendLine("        public string[] Calls { get; }");
            writer.AppendLine("        public string Blob { get; }");
            writer.AppendLine("    }");
            writer.AppendLine("}");
            writer.AppendLine();
        }

        private static void WriteAssemblyAttribute(CodeWriter writer, GraphMethod method, TypeIndex? types) {
            var implementations = new List<string>();
            var services = new List<string>();
            for (var i = 0; i < method.Registrations.Count; i++) {
                var registration = method.Registrations[i];
                implementations.Add(TypeOf(types, registration.ImplementationType));
                for (var s = 0; s < registration.ServiceTypes.Count; s++)
                    services.Add(TypeOf(types, registration.ServiceTypes[s]));
            }

            writer.AppendLine("[assembly: global::Internal.ContainerInstaller(");
            writer.AppendLine("    " + Literal(method.Id) + ",");
            writer.AppendLine("    " + (method.IsRoot ? "true" : "false") + ",");
            writer.AppendLine("    " + Literal(method.File) + ",");
            writer.AppendLine("    " + method.Line.ToString(CultureInfo.InvariantCulture) + ",");
            WriteTypeArray(writer, implementations);
            writer.AppendLine(",");
            WriteTypeArray(writer, services);
            writer.AppendLine(",");
            writer.AppendLine("    new string[] {");
            for (var i = 0; i < method.Calls.Count; i++) {
                var comma = i + 1 < method.Calls.Count ? "," : "";
                writer.AppendLine("        " + Literal(method.Calls[i]) + comma);
            }

            writer.AppendLine("    },");
            writer.AppendLine("    " + Literal(WriteBlob(method)) + ")]");
        }

        private static void WriteTypeArray(CodeWriter writer, List<string> types) {
            writer.AppendLine("    new global::System.Type[] {");
            for (var i = 0; i < types.Count; i++) {
                var comma = i + 1 < types.Count ? "," : "";
                var type = types[i] == VoidSentinel ? "void" : types[i];
                writer.AppendLine("        typeof(" + type + ")" + comma);
            }

            writer.AppendLine("    }");
        }

        private static string TypeOf(TypeIndex? types, string fullyQualified) {
            if (string.IsNullOrEmpty(fullyQualified))
                return VoidSentinel;
            if (types == null)
                return fullyQualified;

            var symbol = types.Find(fullyQualified);
            if (symbol == null)
                return VoidSentinel;
            return TypeNames.ForCode(symbol);
        }

        public static string WriteBlob(GraphMethod method) {
            var builder = new StringBuilder();
            builder.Append(BlobVersion);
            builder.Append('\n');
            builder.Append("calls:");
            for (var i = 0; i < method.CallOrdinals.Count; i++) {
                if (i > 0)
                    builder.Append(',');
                builder.Append(method.CallOrdinals[i].ToString(CultureInfo.InvariantCulture));
            }

            builder.Append('\n');
            for (var i = 0; i < method.Registrations.Count; i++) {
                var registration = method.Registrations[i];
                builder.Append(Escape(registration.Kind));
                builder.Append('|');
                builder.Append(Escape(registration.Lifetime));
                builder.Append('|');
                builder.Append(Escape(registration.Origin));
                builder.Append('|');
                builder.Append(registration.Ordinal.ToString(CultureInfo.InvariantCulture));
                builder.Append('|');
                builder.Append(registration.ServiceTypes.Count.ToString(CultureInfo.InvariantCulture));
                builder.Append('|');
                builder.Append(registration.Arms.Count.ToString(CultureInfo.InvariantCulture));
                builder.Append('|');
                builder.Append(Escape(registration.Hole));
                builder.Append('|');
                builder.Append(Escape(registration.Source));
                builder.Append('|');
                builder.Append(Escape(registration.File));
                builder.Append('|');
                builder.Append(registration.Line.ToString(CultureInfo.InvariantCulture));
                builder.Append('|');
                builder.Append(Escape(registration.ImplementationType));
                builder.Append('\n');
                for (var a = 0; a < registration.Arms.Count; a++) {
                    var arm = registration.Arms[a];
                    builder.Append(Escape(arm.Discriminant));
                    builder.Append('|');
                    builder.Append(Escape(arm.ImplementationType));
                    builder.Append('|');
                    builder.Append(Escape(arm.ParameterExpression));
                    builder.Append('\n');
                }
            }

            return builder.ToString();
        }

        public static string Escape(string value) {
            if (string.IsNullOrEmpty(value))
                return "";
            return value.Replace("\\", "\\\\").Replace("|", "\\|").Replace("\r", "").Replace("\n", "\\n");
        }

        public static string Unescape(string value) {
            if (string.IsNullOrEmpty(value))
                return "";

            var builder = new StringBuilder();
            for (var i = 0; i < value.Length; i++) {
                if (value[i] == '\\' && i + 1 < value.Length) {
                    var next = value[i + 1];
                    if (next == '\\' || next == '|') {
                        builder.Append(next);
                        i++;
                        continue;
                    }

                    if (next == 'n') {
                        builder.Append('\n');
                        i++;
                        continue;
                    }
                }

                builder.Append(value[i]);
            }

            return builder.ToString();
        }

        public static string[] SplitFields(string line) {
            var fields = new List<string>();
            var current = new StringBuilder();
            for (var i = 0; i < line.Length; i++) {
                if (line[i] == '\\' && i + 1 < line.Length) {
                    current.Append('\\');
                    current.Append(line[i + 1]);
                    i++;
                    continue;
                }

                if (line[i] == '|') {
                    fields.Add(current.ToString());
                    current.Clear();
                    continue;
                }

                current.Append(line[i]);
            }

            fields.Add(current.ToString());
            return fields.ToArray();
        }

        private static string Literal(string value) {
            if (value == null)
                value = "";
            return "@\"" + value.Replace("\"", "\"\"") + "\"";
        }
    }
}
