<Project Sdk="Microsoft.NET.Sdk">

    <Sdk Name="Aspire.AppHost.Sdk" Version="13.2.2"/>

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <IsAspireHost>true</IsAspireHost>
        <UserSecretsId>2acdf813-97a1-4c19-92fd-618b39668cb5</UserSecretsId>

        <AssemblyName>Aspire.AppHost</AssemblyName>
        <RootNamespace>Aspire</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.AppHost"/>
        <PackageReference Include="Aspire.Hosting.PostgreSQL"/>
        <PackageReference Include="Aspire.Hosting.Docker"/>
        <PackageReference Include="Npgsql"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\shared\shared.csproj" IsAspireProjectResource="false"/>
        <ProjectReference Include="..\..\Common\Common.csproj" IsAspireProjectResource="false"/>
        <ProjectReference Include="..\..\Infrastructure\Infrastructure.csproj" IsAspireProjectResource="false"/>
        <ProjectReference Include="..\Extensions\Extensions.csproj" IsAspireProjectResource="false"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ConsoleGateway\ConsoleGateway.csproj" />
        <ProjectReference Include="..\Coordinator\Coordinator.csproj"/>
        <ProjectReference Include="..\GameGateway\GameGateway.csproj"/>
        <ProjectReference Include="..\MetaGateway\MetaGateway.csproj"/>
        <ProjectReference Include="..\Silo\Silo.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Content Include="Startup\Migrations\Sql\*.sql">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <Content Include="appsettings.local.json" Condition="Exists('appsettings.local.json')">
            <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
            <Link>appsettings.local.json</Link>
        </Content>
    </ItemGroup>
</Project>
