// Auto-generated by PrefabBuilder. Do not edit manually.
using UnityEngine;

namespace Tools
{
    public static partial class Prefabs
    {
        public static readonly StaticPrefab GlobalAudioListener = new("Global/Global_Audio_Listener");
        public static readonly StaticPrefab GlobalAudioPlayer = new("Global/Global_Audio_Player");
        public static readonly StaticPrefab GlobalCamera = new("Global/Global_Camera");
        public static readonly StaticPrefab GlobalEvents = new("Global/Global_Events");
        public static readonly StaticPrefab GlobalUpdater = new("Global/GlobalUpdater");
        public static readonly StaticPrefab InternalScope = new("Global/InternalScope");
        public static readonly StaticPrefab LoadingScreen = new("Global/LoadingScreen");
    }
}
