using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Internal
{
    public static class ScenesClassGenerator
    {
        private const string LogTag = "ScenesClassGenerator";
        private const string OutputPath = "Assets/Common/Internal/Runtime/Catalogues/Scenes/Scenes.cs";

        public static void Generate(List<(string sceneName, string sceneGuid)> scenes)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// Auto-generated by SceneGenerator. Do not edit manually.");
            sb.AppendLine("using Unity.Scripting.LifecycleManagement;");
            sb.AppendLine();
            sb.AppendLine("namespace Internal");
            sb.AppendLine("{");
            sb.AppendLine("    [NoAutoStaticsCleanup]");
            sb.AppendLine("    public static class Scenes");
            sb.AppendLine("    {");

            foreach (var (sceneName, sceneGuid) in scenes.OrderBy(s => s.sceneName))
            {
                var propertyName = SanitizeIdentifier(sceneName);
                sb.AppendLine($"        public static readonly StaticScene {propertyName} = new(\"{sceneGuid}\");");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            GeneratedFile.WriteIfChanged(LogTag, OutputPath, sb.ToString());
        }

        private static string SanitizeIdentifier(string name)
        {
            var sb = new StringBuilder(name.Length);

            foreach (var c in name)
            {
                if (char.IsLetterOrDigit(c))
                {
                    sb.Append(c);
                }
            }

            return sb.ToString();
        }
    }
}