using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEngine;

namespace Internal
{
    public static class ScenesClassGenerator
    {
        private const string OutputPath = "Assets/Common/Internal/Runtime/Catalogues/Scenes/Scenes.cs";

        public static void Generate(List<(string sceneName, string sceneGuid)> scenes)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// Auto-generated by SceneGenerator. Do not edit manually.");
            sb.AppendLine("namespace Internal");
            sb.AppendLine("{");
            sb.AppendLine("    public static class Scenes");
            sb.AppendLine("    {");

            foreach (var (sceneName, sceneGuid) in scenes.OrderBy(s => s.sceneName))
            {
                var propertyName = SanitizeIdentifier(sceneName);
                sb.AppendLine($"        public static readonly StaticScene {propertyName} = new(\"{sceneGuid}\");");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            var newContent = sb.ToString();

            if (File.Exists(OutputPath))
            {
                var existingContent = File.ReadAllText(OutputPath);

                if (existingContent == newContent)
                    return;
            }

            var directory = Path.GetDirectoryName(OutputPath);
            if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
                Directory.CreateDirectory(directory);

            File.WriteAllText(OutputPath, newContent);
            Debug.Log($"[ScenesClassGenerator] Generated {OutputPath}");
        }

        private static string SanitizeIdentifier(string name)
        {
            var sb = new StringBuilder(name.Length);

            foreach (var c in name)
            {
                if (char.IsLetterOrDigit(c))
                {
                    sb.Append(c);
                }
            }

            return sb.ToString();
        }
    }
}